###########################################################
# Имена действий и перевод для Crosstab
AddLevelHandleAction_Displayname=&Показать/скрыть уровни групп

AddLevelHandleAction_TransName=Показать/скрыть уровни групп

AddMesureViewHandleAction.DisplayName=&Показать/скрыть единицы измерения

AddMesureViewHandleAction.TransName=Показать/скрыть единицы измерения

AddSubTotalAction.LabelName=Итог

AddSubTotalAction.TransName=Редактировать итоги

AddSubTotalAction.DisplayName=&Итоги

AddSubTotalAction.TotalName=ВСЕГО

CrosstabMenuBuilder.EditCubeAction.DisplayName=&Редактировать куб данных

DeleteDimensionViewHandleAction.TransName=Удалить измерение

DeleteDimensionViewHandleAction.DisplayName=&Удалить

DeleteMeasureHandleAction.DisplayName=&Удалить

DeleteMeasureHandleAction.TransName=Удалить единицу измерения

AddComputedMesureHandleAction.DisplayName=Добавить вычисляемую &единицу измерения

AddComputedMesureHandleAction.TransName=Добавить вычисляемую единицу измерения

AddComputedSummaryDialog.Title=Вычисляемая единица измерения

AddComputedSummaryDialog.Label.Name=&Имя:

AddComputedSummaryDialog.Label.Expression=&Выражение:

AddComputedSummaryDialog.Label.DataType=&Тип данных:

AddComputedSummaryDialog.ErrMsg.Msg1=Имя единицы измерения не может быть пустым.

AddComputedSummaryDialog.ErrMsg.Msg2=Это имя единицы измерения уже существует.

AddComputedSummaryDialog.ErrMsg.Msg3=Выражение не может быть пустым.

ShowAsViewAction.DisplayName=Показать как

ShowAsViewAction.TransName=Показать как

MeasureComboPropertyDescriptorProvider.TransName=Изменить ориентацию кросс-таблицы

MeasureHandleDropAdapter_trans_name=Добавить единицу измерения

###########################################################
# Имена команд Crosstab
AddDimensionViewHandleCommand.TransName=Добавить измерение

AddMeasureViewHandleCommand.TransName=Добавить единицу измерения

AddRelativeTimePeriodAction_action_label=Добавить &относительный временной период

AddRelativeTimePeriodAction_trans_label=Добавить относительный временной интервал

ChangeAreaCommand.TransName=Отменить измерение

ChangeMeasureOrderCommand.TransName=Изменить порядок единиц измерения

CreateDimensionViewCommand.TransName=Создать измерение

CreateMeasureViewCommand.TransName=Создать единицу измерения

MergeCrosstabHeaderCellAction_name=&Объединить заголовки

SplitCrosstabHeadCellAction_name=&Разделить заголовок

ExtendedDataColumnXtabDropAdapter.trans.add=Добавить {0}

###########################################################
# EditPart Crosstab
###########################################################
# Имена команд Crosstab
CrosstabTableEditPart.GuideText=Кросс-таблица
###########################################################
# Диалоги Crosstab
GrandTotalProvider.Column.AggregateOn=Агрегировать в

GrandTotalProvider.Column.DataField=Поле данных

GrandTotalProvider.Column.View=Просмотр

GrandTotalProvider.Column.Position=Позиция

GrandTotalProvider.Column.Function=Функции

GrandTotalProvider.ViewStatus=Сохранить текущий вид

GrandTotalProvider.ShowAs=Показать как {0}

SubTotalProvider.Column.DataField=Поле данных

SubTotalProvider.Column.Function=Функции

SubTotalProvider.Column.AggregateOn=Агрегировать в

SubTotalProvider.Column.ViewStatus=Сохранить текущий вид

SubTotalProvider.Column.View=Просмотр

SubTotalProvider.Column.Position=Позиция

SubTotalProvider.ShowAs=Показать как {0}

LevelViewDialog.Title=Показать/скрыть уровни групп

LevelViewDialog.Label.Info=Выберите уровни для отображения в кросс-таблице:

LevelViewDialog.Button.Regular.Text=&Обычная группа

LevelViewDialog.Button.Date.Text=&Группа дат

AggregationDialog.Title=Итоги

AggregationDialog.Label.Grand=Общие итоги:

AggregationDialog.Label.Sub=Промежуточные итоги:

AggregationDialog.TabItem.Title.RowArea=Область строк

AggregationDialog.TabItem.Title.ColumnArea=Область столбцов

ShowSummaryFieldDialog.Title=Показать/скрыть единицы измерения

ShowSummaryFieldDialog.Label.Info=Выберите единицы измерения для отображения в кросс-таблице:

ShowSummaryFieldDialog.Column.Measures=Единицы измерения

ShowSummaryFieldDialog.Column.View=Представления

ShowSummaryFieldDialog.ViewStatus=Сохранить текущий вид

DeleteBindingDialog.Title=Удалить неиспользуемые привязки?

DeleteBindingDialog.Message=Это действие приведет к появлению неиспользуемых привязок данных.\n\nУдалить неиспользуемые привязки?

DeleteBindingDialog.ToggleMessage=&Сохранить ответ
###########################################################
# Узлы структуры Crosstab
AreaNodeProvider.ColumnArea=Область столбцов

AreaNodeProvider.RowArea=Область строк

AreaNodeProvider.DetailArea=Область деталей

CrossTabViewNodeProvider.ColumnArea=Область столбцов

CrossTabViewNodeProvider.RowArea=Область строк

CrossTabCellNodeProvider.Cell=Ячейка

CrossTabLevelNodeProvider.Level=Уровень -

CrossTabMeasureNodeProvider.Detail=Детали -

MeasureSubNodeProvider.Header=Заголовок

MeasureSubNodeProvider.Detail=Детали

MeasureSubNodeProvider.Aggregation=Агрегация

CrosstabSortingModelProvider.ColumnName.GroupLevel=Уровень группы

SortkeyBuilder.DialogTitle.Error.SetSortKey.Title=Ошибка

SortkeyBuilder.DialogTitle.Label.Key=&Ключ:

CrosstabFilterModelProvider.ColumnName.GroupLevelOrMeasure=Цель

CrosstabSortkeyBuilder.DialogTitle.Label.GroupLevel=&Уровень группы:

SortkeyBuilder.DialogTitle.Button.ExpressionBuilder=Нажмите для открытия конструктора выражений

SortkeyBuilder.DialogTitle.Label.Direction=&Направление:

SortkeyBuilder.Label.Locale=&Локаль:

SortkeyBuilder.Label.Strength=&Сила:

SortkeyBuilder.Locale.Auto=Автоматически

###########################################################
# Свойства GrossTabPageGenerator
CrosstabPageGenerator.List.General=Общие

CrosstabPageGenerator.List.Margin=Поля

CrosstabPageGenerator.List.Font=Шрифт

CrosstabPageGenerator.List.Borders=Границы

CrosstabPageGenerator.List.Section=Разрыв страницы

CrosstabPageGenerator.List.Visibility=Видимость

CrosstabPageGenerator.List.TOC=Оглавление

CrosstabPageGenerator.List.Bookmark=Закладка

CrosstabPageGenerator.List.NamedExpressions=Именованные выражения

CrosstabPageGenerator.List.UserProperties=Пользовательские свойства

CrosstabPageGenerator.List.AdvancedProperty=Дополнительно

CrosstabPageGenerator.List.EmptyRowColumn=Пустые строки/столбцы

CrosstabPageGenerator.TabItem.Binding=Привязка

CrosstabPageGenerator.TabItem.RowArea=Область строк

CrosstabPageGenerator.TabItem.ColumnArea=Область столбцов

CrosstabPageGenerator.TabItem.DetailArea=Область деталей

CrosstabPageGenerator.TabItem.Filters=Фильтры

CrosstabPageGenerator.TabItem.Highlights=Выделения

CrosstabPageGenerator.TabItem.map=Сопоставление

CrosstabPageGenerator.TabItem.Sorting=Сортировка

CrosstabGeneralPage.ForEmptyCell=Показывать пустые ячейки &как:

LayoutMeasuresSection.DisplayName=&Ориентация:

CrosstabGeneralPage.HideMeasureHeader=Скрыть заголовок &единиц измерения

###########################################################
# Свойства CrosstabEventHandlerPage
CrosstabEventHandlerPage.dialog.Browse=&Обзор...

###########################################################
# Свойства SortingHandleProvider
SortingHandleProvider.Label.SortOn=Сортировать по:

Element.ReportItem.dataSet=Набор данных:

Element.ReportElement.Cube=Да&нные:

BindingPage.None=Нет

FilterHandleProvider.Label.Filterby=Фильтровать по:

###########################################################
# Свойства EmptyRowColumnProvider
EmptyRowColumnPage.Label.Text=Установите флажок для отображения пустых строк и столбцов на уровне кросс-таблицы

EmptyRowColumnProvider.RowView.Button.Text=Показать пустые &строки

EmptyRowColumnProvider.ColumnView.Button.Text=Показать пустые &столбцы

###########################################################
# Свойства CategoryPageGenerator
CategoryPageGenerator.TabItem.Attributes=Атрибуты


###########################################################
# Свойства диалога FilterConditionBuilder
FilterConditionBuilder.DialogMessage.Edit=

FilterConditionBuilder.DialogMessage.New=

FilterConditionBuilder.DialogTitle.New=Новое условие фильтра

FilterConditionBuilder.DialogTitle.Edit=Редактировать условие фильтра

FilterConditionBuilder.choice.ValueOfThisDataItem=Значение этого элемента данных

FilterConditionBuilder.tooltip.ExpBuilder=Нажмите для открытия конструктора выражений.

FilterConditionBuilder.text.AND=И

FilterConditionBuilder.text.Condition=&Условие фильтра:

FilterConditionBuilder.text.GroupLevel=&Уровень группы:

FilterConditionBuilder.list.item1=Значение

FilterConditionBuilder.button.edit=&Редактировать...

FilterConditionBuilder.button.delete=&Удалить

FilterConditionBuilder.button.deleteall=Удалить &все

FilterConditionBuilder.button.add=&Добавить

FilterConditionBuilder.button.edit.tooltip=Редактировать выбранное значение в списке значений

FilterConditionBuilder.button.delete.tooltip=Удалить выбранное значение из списка

FilterConditionBuilder.button.deleteall.tooltip=Удалить все значения из списка

FilterConditionBuilder.button.add.tooltip=Добавить значение в список значений

CrosstabFilterConditionBuilder.Item.Decorator=--------

CrosstabFilterConditionBuilder.Button.Detal=&Детали

CrosstabFilterConditionBuilder.Item.SelectLevel=---Выбрать уровень---

CrosstabFilterConditionBuilder.Item.SelectMeasure=---Выбрать меру---

CrosstabFilterConditionBuilder.DialogMessage.New=Выберите целевой уровень группы или меру, к которой будет применен фильтр, затем задайте условие фильтра.

CrosstabFilterConditionBuilder.DialogMessage.Edit=Выберите целевой уровень группы или меру, к которой будет применен фильтр, затем задайте условие фильтра.

CrosstabFilterConditionBuilder.label.value=Значение

CrosstabFilterConditionBuilder.Label.Target=Цель:

CrosstabFilterConditionBuilder.Button.GroupLevel=&Уровень группы

CrosstabFilterConditionBuilder.Button.Measure=&Единица измерения

CrosstabFilterConditionBuilder.Button.Cube=&Куб

FilterbyTree.Bindings.Catogory.Measures=Единица измерения

FilterbyTree.Bindings.Catogory.Dimension=Измерение

FilterbyTree.Bindings.Catogory.GrandTotal=Общий итог

FilterbyTree.Bindings.Catogory.SubTotal=Промежуточный итог

FilterbyTree.Bindings.Catogory.OtherType=Другой тип

FilterbyTree.Bindings.Catogory.Undefined=Не определено

FilterbyTree.Title=Фильтровать по

FilterbyTree.Message=Фильтровать по

###########################################################
# VirtualCellEditPart.java
Blank.text.column=Перетащите поле(я) данных сюда для определения столбцов

Blank.text.row=Перетащите поле(я) данных,\nчтобы определить здесь строки

Blank.text.measure=Перетащите поле(я) данных для их агрегации здесь

###########################################################
# CrosstabGrandTotalDialog
CrosstabGrandTotalDialog.Title=Общий итог

CrosstabGrandTotalDialog.Text.DataField=&Поле данных:

CrosstabGrandTotalDialog.Text.Function=&Функция:


###########################################################
# Разрыв страницы области строк Crosstab
CrosstabPageBreakProvider.Column.GroupLevel=Уровень группы

CrosstabPageBreakProvider.Column.Before=До

CrosstabPageBreakProvider.Column.After=После

CrosstabPageBreakProvider.Column.Inside=Внутри

CrosstabPageBreakProvider.Column.Interval=Интервал

###########################################################
# Промежуточный итог области строк Crosstab
CrosstabSubToatalProvider.Column.AggregateOn=Агрегировать в

CrosstabSubToatalProvider.Column.DataField=Поле данных

CrosstabSubToatalProvider.Column.Function=Функция

###########################################################
# CrosstabPageBreakDialog
CrosstabPageBreakDialog.Title=Разрыв страницы

CrosstabPageBreakDialog.Text.GroupLevel=&Уровень группы:

CrosstabPageBreakDialog.Text.PageBreakBefore=&До:

CrosstabPageBreakDialog.Text.PageBreakAfter=&После:

CrosstabPageBreakDialog.Text.PageBreakInside=&Внутри:

CrosstabPageBreakDialog.Text.PageBreakInterval=&Интервал разрыва страницы:

###########################################################
# SubTotalDialog
SubTotalDialog.Title=Промежуточный итог

SubTotalDialog.Text.AggregateOn=&Агрегировать в:

SubTotalDialog.Text.Function=&Функция:

SubTotalDialog.Text.DataField=&Поле данных:

FormPage.Menu.ModifyProperty=Редактировать

CrosstabPageGenerator.List.SubTotals=Промежуточные итоги

CrosstabPageGenerator.List.GrandTotals=Общие итоги

CrosstabPageGenerator.List.PageBreak=Разрыв страницы

PageLayoutPropertyDescriptorProvider.PageLayout=Макет страницы:

RowPageBreak.RepeatColumnHeader=&Повторять заголовок столбца

ColumnPageBreak.RepeatRowHeader=Повторять заголовок &строки

###########################################################
# Свойства ExpressionValueCellEditor
ExpressionValueCellEditor.buildExpressionAction=<Конструктор выражений...>

ExpressionValueCellEditor.selectValueAction=<Выбрать значение...>

ExpressionValueCellEditor.filterBy=<Фильтровать по...>

ExpressionValueCellEditor.title=Выбрать значение

CrosstabSortKeyBuilder.Label.SelColumnMemberValue=Выбрать значение члена столбца

CrosstabSortKeyBuilder.Label.SelRowMemberValue=Выбрать значение члена строки

CrosstabFilterConditionBuilder.Label.SelColumnMemberValue=Выбрать значение члена столбца

CrosstabFilterConditionBuilder.Label.SelRowMemberValue=Выбрать значение члена строки

CrosstabFilterConditionBuilder.DialogTitle.Label.GroupLevel=&Уровень группы:

CrosstabFilterConditionBuilder.DialogTitle.Label.Measure=&Единица измерения:

SelColumnMemberValue.Column.Level=Уровень

SelColumnMemberValue.Column.Value=Значение

ChoiceSetFactory.choice.None=Нет

###########################################################
# Свойства SelectValueDialog
SelectValueDialog.errorRetrievinglist=Ошибка при получении списка

SelectValueDialog.messages.error.selectVauleUnavailable=Не удалось получить значение для выражения.

SelectValueDialog.noExpressionSet=Выражение не указано.

SelectValueDialog.retrieving=Получение списка...

SelectValueDialog.selectValue=Выбрать значение

SelectValueDialog.messages.info.selectVauleUnavailable=Список значений недоступен.

CrosstabPreferencePage.Title=Кросс-таблица

CrosstabPreferencePage.filterLimit=Лимит фильтра

CrosstabPreferencePage.filterLimit.prompt=Максимальное количество отображаемых &значений:

CrosstabPreferencePage.Error.MaxRowInvalid=Недопустимое числовое значение.

CrosstabPreferencePage.autoDelBindings.Text=Удалять неиспользуемые привязки после изменений структуры кросс-таблицы

CrosstabPreferencePage.autoDelBindings.Text.Prompt=&Запрашивать

CrosstabPreferencePage.autoDelBindings.Text.Always=&Всегда

CrosstabPreferencePage.autoDelBindings.Text.Never=&Никогда

CrosstabPreferencePage.promptGroup=Запрос

CrosstabPreferencePage.cubePopup.Text=&Предупреждение после перемещения полей в кросс-таблицу и успешного создания куба

###########################################################
# Свойства привязки данных Crosstab
CrosstabDataBinding.title.ChangeCube=Изменить куб?

CrosstabDataBinding.message.changeCube=Вы собираетесь изменить привязку данных кросс-таблицы.\n\nУдалить все существующие привязки столбцов данных?

###########################################################
# Свойства Crosstab DropAdapter
DataColumnXTabDropAdapter.DataCube=Куб данных

CubeBuilder.warning.title=Кросс-таблица

CubeBuilder.warning.message=Куб данных успешно создан.\nДля завершения создания кросс-таблицы перетащите поля из созданного куба данных в контейнер кросс-таблицы.

CubeBuilder.warning.prompt=&Не показывать это сообщение снова

###########################################################
# Трекер перетаскивания Crosstab
CrosstabColumnDragTracker.ResizeColumn=Изменить размер столбца

CrosstabColumnDragTracker.Show.Label=Ширина:

CrosstabRowDragTracker.Show.Label=Высота:

###########################################################
# AggregationCellTextViewProvider
AggregationCellTextViewProvider.displayName=Текст


###########################################################
# Свойства CrosstabSortKeyBuilder
CrosstabSortKeyBuilder.choice.ValueOfThisDataItem=Значение этого элемента данных

CrosstabSortKeyBuilder.tooltip.ExpBuilder=Открыть конструктор выражений

CrosstabSortKeyBuilder.MSG.CreateNew=Новый...

InsertCubeInLayoutAction.menu.text=&Редактировать

InsertCubeInLayoutAction.action.text=Вставить в макет

InsertCubeInLayoutAction.action.message=Создать кросс-таблицу из куба

MapRuleBuilderDialog.MsgDlg.Title=Предупреждение

MapRuleBuilderDialog.MsgDlg.Msg=Значение не может быть пустым.

LevelHandleDropAdapter.ActionText=Добавить измерение

LevelPropertyDialog.MSG.CreateNew=


###########################################################
# Свойства CrosstabHighlightRuleBuilder
CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstab=Кросс-таблица

CrosstabHighlightRuleBuilderDialog.text.Description.Element.Crosstabcell=Ячейка кросс-таблицы

CrosstabHighlightRuleBuilderDialog.text.Description.Element.ReportElement=Элемент отчета

CrosstabHighlightRuleBuilderDialog.text.Description=Применить условное форматирование к {0}. Укажите выражение условия и формат.\nФормат будет применен, если выражение вычислится как TRUE.

###########################################################
# Свойства CrosstabFilterConditionBuilder
CrosstabFilterConditionBuilder.ExpressionEditor.Title=Редактор выражений

CrosstabFilterConditionBuilder.MsgDlg.Msg=Предупреждение

CrosstabFilterConditionBuilder.MsgDlg.Title=Значение не может быть пустым.

CrosstabFilterConditionBuilder.Button.UpdateAggregation=&Пересчитать итоги

###########################################################
# Свойства Breadcrumb provider
VirtualCrosstabCellNodeProvider.Display.ColumnArea=Область столбцов

VirtualCrosstabCellNodeProvider.Display.DetailArea=Область деталей

VirtualCrosstabCellNodeProvider.Display.RowArea=Область строк

VirtualCrosstabCellNodeProvider.Display.UnknownArea=Неизвестная область

CrosstabBindingComboPropertyDescriptorProvider.Flag.DataModel=\ (модель данных)

CrosstabBindingRefresh.action.message=Обновить привязки кросс-таблицы