###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Конфигурация плагина
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
#
###############################################################################
# Строки NLS
###############################################################################
#
plugin.name=Драйвер времени выполнения ODA источника данных подключения к базе данных JDBC
data.source.name=Подключение к базе данных JDBC для конструктора запросов

data.set.name=SQL-запрос выбора [Конструктор запросов]

connection.profile.name=Профиль подключения к базе данных JDBC
dataset.property.parameterMetaData=Метаданные параметров JDBC
datasource.property.username=&Имя пользователя

datasource.property.password=&Пароль

datasource.property.jdbcURL=U&RL драйвера JDBC

datasource.property.driverClass=&Класс драйвера JDBC

datasource.property.jarlist=&Список JAR-файлов драйвера JDBC

datasource.property.databasename=&База данных