ChartImpl.ChartTitle=Заголовок диаграммы

ChartImpl.AltText=Эта диаграмма не содержит данных.

ChartWithAxesImpl.X_Axis.title=Заголовок оси X

ChartWithAxesImpl.Y_Axis.title=Заголовок оси Y

ChartWithAxesImpl.Z_Axis.title=Заголовок оси Z

ChartWithoutAxesImpl.Unsupported3Dimension=Круговая диаграмма не поддерживает 3D.

exception.convert.double=Невозможно преобразовать значение {0} в число с плавающей точкой

exception.data.outofsync=Входные данные не синхронизированы; ряд категорий содержит {0} значений; ряд значений содержит {1} значений.

exception.out.of.bounds=За пределами допустимых границ

exception.step.zoom.out=Невозможно выполнить zoomOut для шага={0}

exception.no3d.support=3D-диаграммы пока не поддерживаются

exception.curve.label.position.not.supported=Позиция надписи [{0}] не поддерживается при кривой аппроксимации.

exception.convert.calendar=Невозможно преобразовать значение {0} в значение календаря

exception.anchor.transpose=Невозможно транспонировать якорь {0} для ориентации оси {1}

exception.tick.computations=Ошибка при вычислении шкалы

exception.curve.visibility.unset=Для атрибутов линии кривой должна быть установлена видимость

exception.angle.range.transpose=[Угол={0}] не может быть транспонирован за пределы диапазона (90 >= 0 >= -90)

exception.legend.direction.tblr=Направление легенды не было явно установлено как сверху-вниз или слева-направо

exception.scale.null.location=Не удалось найти координату для нулевого значения на шкале {0}

exception.illegal.icon.palette.type.for.marker=''{0}'' не является допустимым типом изображения для значка маркера.

exception.illegal.filltype.crosshair.marker=Цвет палитры не может быть установлен для маркера-CROSSHAIR как {0}

exception.illegal.filltype.cross.marker=Цвет палитры не может быть установлен для маркера-CROSS как {0}

exception.invalid.step.size =Установлено недопустимое значение "step size({0}) <= 0" для шкалы оси

exception.invalid.step.number =Установлено недопустимое значение ''step number({0}) < 1'' для шкалы оси

exception.curve.line.visibility.not.defined=Свойство "Видимость" линии кривой определено некорректно.

exception.min.largerthan.max=Установлены недопустимые значения "min({0}) > max({1})" для шкалы оси

exception.combination.axis.label.position=Неожиданная комбинация ось={0} и позиция надписи={1}

exception.cannot.locate.start.marker.range=Не удалось найти начало диапазона для значения {0} в диапазоне маркера {1}

exception.cannot.locate.value.marker.line=Не удалось найти значение {0} в линии маркера {1}

exception.combination.axis.tick.style=Неожиданная комбинация ось={0} и тип штриха={1}

exception.invalid.axis.data.type=Указанный тип данных для оси не соответствует значению поля данных: ({0})

exception.undefined.axis.data.type=Тип данных не определён для оси {0}

exception.unsupported.compare.text=Сравнение текстовых элементов данных не поддерживается

exception.unsupported.comparison=Объект {0} не может быть частью сравнения с предыдущими версиями

exception.unsupported.internal.draw={0} не может быть нарисован внутренним способом через событие

exception.unsupported.internal.fill={0} не может быть заполнен внутренним способом через событие

exception.unsupported.chart.model=Невозможно вычислить диаграмму, определённую моделью [{0}]

exception.unsupported.bounds=Невозможно вычислить границы для события {0}

exception.unsupported.copy=Невозможно создать копию события {0}

exception.unsupported.step.number=Номер шага не поддерживается для нечислового значения.

exception.undefined.data.point=Значение DataPoint, связанное с определением ряда данных, не определено

exception.unit.size.failure=Невозможно вычислить размер единицы, так как координаты шкалы не определены

exception.process.content.type=Невозможно обработать содержимое набора данных, установленное как {0} для типа {1}

exception.undefined.axis.label.visibility=Видимость для надписей оси {0} не определена

exception.undefined.axis.title.visibility=Видимость для заголовков оси {0} не определена

exception.undefined.axis.label.position=Позиция надписи для оси {0} не определена

exception.undefined.axis.title.position=Позиция заголовка для оси {0} не определена

exception.undefined.data.label.position=Позиция надписи данных для ряда данных {0} не определена

exception.undefined.axis.type=Тип оси не определён для оси

exception.unset.series.stacked.property=Свойство ''Стекировано'' не было явно установлено для стекируемого ряда данных {0}.

exception.undefined.axis.major.tick.style=Стиль основной шкалы сетки для оси {0} не определён

exception.undefined.axis.minor.tick.style=Стиль дополнительной шкалы сетки для оси {0} не определён

exception.zero.negative.logarithmic.scale=Логарифмическая шкала не должна содержать нулевые или отрицательные значения

exception.illegal.vaxis.label.position=Установлено недопустимое значение позиции надписи {0} для вертикальной оси {1}

exception.illegal.vaxis.title.position=Установлено недопустимое значение позиции заголовка {0} для вертикальной оси {1}

exception.illegal.vaxis.major.tick.style=Установлен недопустимый стиль основной шкалы как {0} для вертикальной оси {1}

exception.illegal.vaxis.minor.tick.style=Установлен недопустимый стиль дополнительной шкалы как {0} для вертикальной оси {1}

exception.illegal.haxis.label.position=Установлено недопустимое значение позиции надписи {0} для горизонтальной оси {1}

exception.illegal.haxis.title.position=Установлено недопустимое значение позиции заголовка {0} для горизонтальной оси {1}

exception.illegal.rotation.angle.label=Угол поворота (-90 <= УГОЛ <= 90) установлен недопустимо для надписи {0}

exception.illegal.rendering.direction=Установлен недопустимый аргумент для направления отображения легенды = {0}

exception.illegal.rendering.orientation=Установлен недопустимый аргумент для ориентации отображения легенды = {0}

exception.illegal.legend.direction=Установлен недопустимый аргумент для направления отображения легенды = {0}

exception.illegal.null.value=Передан недопустимый нулевой аргумент для создания диаграммы

exception.cannot.find.plugin.entry=Не найдены значения для поиска={0}; элемент=({1}:{2}) во всех файлах "plugin.xml" всех доступных плагинов

exception.cannot.split.major=Невозможно разделить основную единицу на {0} дополнительную(ые) единицу(ы).

exception.illegal.legend.orientation=Установлен недопустимый аргумент для ориентации отображения легенды = {0}

exception.cwoa.single.runtime.series=Диаграммы без осей могут содержать только один ряд данных времени выполнения

exception.illegal.haxis.major.tick.style=Установлен недопустимый стиль основной шкалы как {0} для горизонтальной оси {1}

exception.illegal.haxis.minor.tick.style=Установлен недопустимый стиль дополнительной шкалы как {0} для горизонтальной оси {1}

exception.client.area.outline.visibility=Не установлена видимость для контура клиентской области

exception.cannot.locate.end.marker.range=Не удалось найти конец диапазона для значения {0} в диапазоне маркера {1}

exception.runtime.dataset.count.mismatch=Обнаружено несоответствие ({0}\!={1}) количества наборов данных в стекированном ряду данных времени выполнения

exception.illegal.base.runtime.series.count=Количество рядов данных категорий времени выполнения (здесь {0}) для диаграммы без осей должно быть равно 1

exception.unstackable.is.stacked=Ряд данных {0}, который не может быть стекирован, установлен как стекированный

exception.unset.label.visibility=Для надписи {0} не установлена видимость

exception.marker.line.null.value=Невозможно нарисовать линию рендеринга для нулевого значения, как определено в линии маркера {0}

exception.unset.axis.visibility=Не установлена видимость оси; это приводит к неоднозначным результатам

exception.unset.line.visibility=Не была явно установлена видимость атрибутов линии в {0}

exception.stacked.datetime.axis.series=Стекированный ряд данных не может быть определён на оси даты/времени.

exception.stacked.unstacked.mix.series=Определение ряда данных {0} содержит комбинацию стекированных и нестекированных рядов данных.

exception.internal.stack.series.setup=Стекированный ряд данных для оси {0} определён некорректно

exception.invalid.minimum.scale.value=Установлено недопустимое минимальное значение шкалы {0} для типа оси {1}

exception.invalid.maximum.scale.value=Установлено недопустимое максимальное значение шкалы {0} для типа оси {1}

exception.legend.orientation.horzvert=Ориентация легенды не была явно установлена как горизонтальная или вертикальная

exception.legend.orientation.InvalidMaxPercent=Максимальный процент должен быть между 0 и 1.

info.processing.stacked.info=Обрабатывается информация о стекировании для оси {0}

info.eclenv.creating.device=(ECLIPSE-ENV) Создаётся устройство {0} как {1}

info.stdenv.creating.device=(STANDALONE-ENV) Создаётся устройство {0} как {1}

info.eclenv.creating.display=(ECLIPSE-ENV) Создаётся сервер отображения {0} как {1}

info.stdenv.creating.display=(STANDALONE-ENV) Создаётся сервер отображения {0} как {1}

exception.percent.stacked.non.numerical=Невозможно вычислить процентную/стекированную ось с нечисловыми данными

exception.text.data.numerical.datetime.axis=Невозможно использовать текстовые данные для рендеринга числовой оси или оси даты/времени.

exception.numerical.data.datetime.axis=Невозможно использовать данные, не относящиеся к дате или времени, для рендеринга оси даты/времени.

exception.datetime.data.numerical.axis=Невозможно использовать нечисловые данные для рендеринга числовой оси.

exception.cwoa.single.series.definition=Диаграммы без осей могут содержать только одно определение ряда данных

exception.parse.value.format.specifier=Не удалось проанализировать значение {0} со спецификатором формата {1}

exception.orthogonal.axis.numerical.datetime=Ось значений может иметь только числовой формат или формат даты/времени

exception.axis.series.link.broken=Не удалось найти определение оси для ряда данных {0}

exception.process.content.dataset=Невозможно обработать содержимое набора данных, установленное как {0} для набора данных {1}

exception.base.orthogonal.inconsistent.count=Ось категорий содержит {0} объектов; ось значений содержит {1} объектов.

exception.base.orthogonal.null.datapoint=Указанные точки данных содержат недопустимое нулевое значение.

exception.base.orthogonal.null.datadefinition=Указанное выражение определения данных недопустимо.

exception.dataset.non.numerical.to.numerical=В наборе данных обнаружен неожиданный нечисловой тип данных {0}; преобразование в числовое значение невозможно.

exception.dataset.non.datetime=Тип данных, привязанный к оси X, не имеет формат "Дата/Время"

exception.scale.tick.max=Невозможно отрендерить слишком много линий сетки. Настройте шаг шкалы или единицу шкалы.

exception.unknown.axis.type.tick.computations=Невозможно определить тип оси для вычисления делений шкалы

exception.unknown.trigger.datatype=Данные триггера недопустимы или тип неизвестен.

exception.unsupported.compare.unknown.objects=Указаны неподдерживаемые элементы данных для сравнения DE1={0} и DE2={1}

exception.unsupported.compare.different.objects=Указаны смешанные элементы данных для сравнения DE1={0} и DE2={1}

exception.resultset.data.type.retrieval.failed=Не удалось определить типы данных из результата

exception.base.axis.no.series.definitions=Основная ось категорий не содержит определений рядов данных

exception.no.stack.percent.3D.chart=Функции стекирования и процентов не поддерживаются в 3D-диаграммах.

exception.dial.dimension="{0}" не поддерживается рядом данных индикатора.

exception.pie.dimension="{0}" не поддерживается рядом данных круговой диаграммы.

exception.scatter.dimension="{0}" не поддерживается рядом данных точечной диаграммы.

exception.stock.dimension="{0}" не поддерживается рядом данных диаграммы котировок.

exception.multi.orthogonal.3D.not.supported=3D-диаграммы поддерживают только одну ось значений.

exception.scatter.3D.not.supported=Ось категорий точечной диаграммы не поддерживается 3D-диаграммами.

exception.no.transposed.3D.chart=Транспонирование не поддерживается 3D-диаграммами.

exception.3D.points.length.less.than.3=Длина списка точек для события рендеринга 3D должна быть не менее 3 (>=3).

exception.unsupported.area3d.getOjbect3D=Прямой доступ Area3DRenderEvent к Object3D не поддерживается. Для обработки каждого дочернего I3DRenderEvent повторите операцию.

exception.javascript.error={0} в строке {1} скрипта диаграммы:''{2}''

exception.null.legend.layout.hints=Невозможно отрендерить легенду с подсказками макета 'null' для объекта.

exception.null.legend.item.hints=Невозможно отрендерить элемент легенды с подсказками элемента 'null' для объекта.

info.elapsed.render.time=Время полного рендеринга = {0} мс

info.elapsed.time.render=Время полного рендеринга = {0} мс

info.eclenv.creating.dsp=(ECLIPSE-ENV) Создаётся DataSetProcessor {0}

info.datapoint.to.string={0}:{1}
info.stdenv.creating.dsp=(STANDALONE-ENV) Создаётся DataSetProcessor {0}

constant.undefined.string=<не определено>

constant.null.string=Null

error.invalid.enumerator=Значение ''{0}'' не является допустимым перечислителем ''{1}''

error.invalid.classifier=Тип данных ''{0}'' не является допустимым классификатором

error.invalid.argument.for.barSeries={0} является недопустимым аргументом для BarSeriesImpl. Модель диаграммы должна быть экземпляром org.eclipse.birt.chart.model.ChartWithAxes.

error.invalid.argument.for.lineSeries={0} является недопустимым аргументом для LineSeriesImpl. Модель диаграммы должна быть экземпляром org.eclipse.birt.chart.model.ChartWithAxes.

error.invalid.argument.for.stockSeries={0} является недопустимым аргументом для StockSeriesImpl. Модель диаграммы должна быть экземпляром org.eclipse.birt.chart.model.ChartWithAxes.

error.legend.position=Позиция блока легенды должна быть указана для корректного отображения компонентов диаграммы.

error.null.source=Исходное значение не должно быть Null

error.unknown.palette=Запрошена неизвестная палитра {0}, используется палитра по умолчанию

error.type.not.set=Не установлен ТИП для этого экземпляра DateFormatSpecifier.

error.eclenv.cannot.find.dsp=(ECLIPSE-ENV) Не найдена реализация DataSetProcessor для {0}

error.stdenv.cannot.find.dsp=(STANDALONE-ENV) Не найдена реализация DataSetProcessor для {0}

info.eclenv.creating.series.renderer=(ECLIPSE-ENV) Создаётся рендерер ряда данных {0}

info.eclenv.creating.datapoint.definition=(ECLIPSE-ENV) Создаётся определение точки данных {0}

error.eclenv.cannot.find.series.renderer=(ECLIPSE-ENV) Не найдена реализация рендерера ряда данных для {0}

info.stdenv.creating.series.renderer=(STANDALONE-ENV) Создаётся рендерер ряда данных {0}

info.compute.elapsed.time.without.axes=Время вычисления диаграммы (без осей) = {0} мс

info.compute.elapsed.time.with.axes=Время вычисления диаграммы (с осями) = {0} мс

error.stdenv.cannot.find.series.renderer=(STANDALONE-ENV) Не найдена реализация рендерера ряда данных для {0}

error.stdenv.cannot.find.datapoint.definition=(STANDALONE-ENV) Не найдена реализация определения точки данных для {0}

error.eclenv.cannot.find.device=(ECLIPSE-ENV) Не найдена реализация рендерера устройства для {0}

error.stdenv.cannot.find.device=(STANDALONE-ENV) Не найдена реализация рендерера устройства для {0}

error.eclenv.cannot.find.display=(ECLIPSE-ENV) Не найдена реализация сервера отображения для {0}

error.stdenv.cannot.find.display=(STANDALONE-ENV) Не найдена реализация сервера отображения для {0}

info.log.script=[СКРИПТ]: {0}

info.render.series={0}: renderSeries() [{1}/{2}]
info.log.info=[ИНФО]: {0}

info.log.warn=[ПРЕДУПР]: {0}

info.log.err=[ОШИБКА]: {0}

info.log.fatal=[КРИТИЧ]: {0}

prefix.marker.range.caption=[
separator.marker.range.caption=\ до

suffix.marker.range.caption=]
wrapped.instruction.to.string={0}: Модель={1}; Границы={2}

exception.mixed.data.types=При агрегатной функции {0} обнаружены смешанные входные данные для сводки

info.eclenv.creating.function=(ECLIPSE-ENV) Создаётся агрегатная функция {0}

error.eclenv.cannot.find.function=(ECLIPSE-ENV) Не найдена реализация агрегатной функции для {0}

info.stdenv.creating.function=(STANDALONE-ENV) Создаётся агрегатная функция {0}

error.stdenv.cannot.find.function=(STANDALONE-ENV) Не найдена реализация агрегатной функции для {0}

Info.try.load.java.handler=Загружается класс обработчика Java-событий диаграммы...

Info.java.handler.loaded=Загружен класс обработчика Java-событий диаграммы [{0}].

Info.invalid.java.handler=Обнаружен недопустимый класс обработчика Java-событий диаграммы [{0}] и проигнорирован.

Info.try.register.javascript.content=Загружается JavaScript-содержимое диаграммы...

Info.javascript.content.registered=JavaScript-содержимое диаграммы загружено.

warn.unspecified.sorting=Не указана сортировка для {0}.

##################################################
# Attributes 
#
# !!the key is bound to those attribute literal' name value, 
# !!if that changes, this must be updated accordingly.
#
SeriesImpl.displayName=Простой ряд данных

AreaSeriesImpl.displayName=Ряд данных диаграммы областей

BarSeriesImpl.displayName=Ряд данных столбчатой диаграммы

BarSeriesImpl.coneDisplayName=Ряд конусов

BarSeriesImpl.tubeDisplayName=Ряд труб

BarSeriesImpl.pyramidDisplayName=Ряд пирамид

DialSeriesImpl.displayName=Ряд данных диаграммы индикатора

LineSeriesImpl.displayName=Ряд данных линейной диаграммы

PieSeriesImpl.displayName=Ряд данных круговой диаграммы

ScatterSeriesImpl.displayName=Ряд данных точечной диаграммы

StockSeriesImpl.displayName=Ряд данных диаграммы котировок

BubbleSeriesImpl.displayName=Ряд пузырей

GanttSeriesImpl.displayName=Ряд Ганта

DifferenceSeriesImpl.displayName=Ряд разности

AxisType.Linear.displayName=Линейная

AxisType.Logarithmic.displayName=Логарифмическая

AxisType.Text.displayName=Текст

AxisType.DateTime.displayName=Дата/Время
IntersectionType.Min.displayName=Мин

IntersectionType.Max.displayName=Макс

IntersectionType.Value.displayName=Значение

ScaleUnitType.Seconds.displayName=Секунды

ScaleUnitType.Minutes.displayName=Минуты

ScaleUnitType.Hours.displayName=Часы

ScaleUnitType.Days.displayName=Дни

ScaleUnitType.Weeks.displayName=Недели

ScaleUnitType.Months.displayName=Месяцы

ScaleUnitType.Quarters.displayName=Кварталы

ScaleUnitType.Years.displayName=Годы

SortOption.Ascending.displayName=По возрастанию

SortOption.Descending.displayName=По убыванию

TriggerCondition.MouseHover.displayName=Наведение мыши (Устарело)

TriggerCondition.MouseClick.displayName=Щелчок мыши (Устарело)

TriggerCondition.onclick.displayName=Щелчок мыши

TriggerCondition.ondblclick.displayName=Мышь: Двойной щелчок

TriggerCondition.onmousedown.displayName=Мышь: Нажатие

TriggerCondition.onmouseup.displayName=Мышь: Отпускание

TriggerCondition.onmouseover.displayName=Наведение мыши

TriggerCondition.onmousemove.displayName=Мышь: Перемещение

TriggerCondition.onmouseout.displayName=Уход мыши

TriggerCondition.onfocus.displayName=Фокус

TriggerCondition.onblur.displayName=Потеря фокуса

TriggerCondition.onkeydown.displayName=Клавиша: Нажатие

TriggerCondition.onkeypress.displayName=Клавиша: Нажатие с удержанием

TriggerCondition.onkeyup.displayName=Клавиша: Отпускание

TriggerCondition.onload.displayName=Загрузка

ActionType.URLRedirect.displayName=Гиперссылка

ActionType.ShowTooltip.displayName=Показать подсказку

ActionType.ToggleVisibility.displayName=Переключить видимость

ActionType.InvokeScript.displayName=Выполнить скрипт

ActionType.Highlight.displayName=Выделить

ActionType.CallBack.displayName=Обратный вызов

ActionType.ToggleDataPointVisibility.displayName=Переключить видимость точки данных

TickStyle.Across.displayName=Поперёк

TickStyle.Left.displayName=Слева

TickStyle.Right.displayName=Справа

TickStyle.Above.displayName=Сверху

TickStyle.Below.displayName=Снизу

DataPointComponentType.BaseValue.displayName=Данные категории

DataPointComponentType.OrthogonalValue.displayName=Данные значений

DataPointComponentType.SeriesValue.displayName=Имя ряда значений

DataPointComponentType.PercentileOrthogonalValue.displayName=Данные процентильного значения

LeaderLineStyle.FixedLength.displayName=Фиксированная длина

LeaderLineStyle.StretchToSide.displayName=Растянуть в сторону

MarkerType.Crosshair.displayName=Перекрестие

MarkerType.Triangle.displayName=Треугольник

MarkerType.Box.displayName=Прямоугольник

MarkerType.Circle.displayName=Круг

MarkerType.Icon.displayName=Значок

MarkerType.Nabla.displayName=Набла

MarkerType.Diamond.displayName=Ромб

MarkerType.FourDiamonds.displayName=Четыре ромба

MarkerType.Ellipse.displayName=Эллипс

MarkerType.SemiCircle.displayName=Полукруг

MarkerType.Hexagon.displayName=Шестиугольник

MarkerType.Rectangle.displayName=Прямоугольник

MarkerType.Star.displayName=Звезда

MarkerType.Column.displayName=Столбец

MarkerType.Cross.displayName=Крест

RiserType.Rectangle.displayName=Прямоугольник

RiserType.Triangle.displayName=Треугольник

RiserType.Tube.displayName=Труба

RiserType.Cone.displayName=Конус

Anchor.North.displayName=Сверху

Anchor.NorthEast.displayName=Сверху справа

Anchor.East.displayName=Справа

Anchor.SouthEast.displayName=Снизу справа

Anchor.South.displayName=Снизу

Anchor.SouthWest.displayName=Снизу слева

Anchor.West.displayName=Слева

Anchor.NorthWest.displayName=Сверху слева

AnchorVertical.North.displayName=Сверху

AnchorVertical.South.displayName=Снизу

AnchorVertical.West.displayName=По центру

AnchorHorizontal.East.displayName=Справа

AnchorHorizontal.South.displayName=По центру

AnchorHorizontal.West.displayName=Слева

AutoScale.Exception.IsInfiite=\ бесконечно

AutoScale.Exception.IsNaN=\ не является числом

AutoScale.ValueName.StepSize=Размер шага

Stretch.Horizontal.displayName=По горизонтали

Stretch.Vertical.displayName=По вертикали

Stretch.Both.displayName=Оба

Orientation.Horizontal.displayName=По горизонтали

Orientation.Vertical.displayName=По вертикали

Direction.LeftRight.displayName=Слева направо

Direction.TopBottom.displayName=Сверху вниз

LegendItemType.Series.displayName=Ряд значений

LegendItemType.Categories.displayName=Категории

Position.Above.displayName=Сверху

Position.Below.displayName=Снизу

Position.Left.displayName=Слева

Position.Right.displayName=Справа

Position.Inside.displayName=Внутри

Position.Outside.displayName=Снаружи

UnitsOfMeasurement.Pixels.displayName=Пиксели

UnitsOfMeasurement.Points.displayName=Точки

UnitsOfMeasurement.Inches.displayName=Дюймы

UnitsOfMeasurement.Centimeters.displayName=Сантиметры

DataType.Numeric.displayName=Числовой

DataType.DateTime.displayName=Дата/Время
DataType.Text.displayName=Текст

GroupingUnitType.Seconds.displayName=Секунды

GroupingUnitType.Minutes.displayName=Минуты

GroupingUnitType.Hours.displayName=Часы

GroupingUnitType.Days.displayName=Дни

GroupingUnitType.Weeks.displayName=Недели

GroupingUnitType.Months.displayName=Месяцы

GroupingUnitType.Years.displayName=Годы

GroupingUnitType.Quarters.displayName=Кварталы

GroupingUnitType.String.displayName=Строка

GroupingUnitType.StringPrefix.displayName=Префикс строки

DateFormatType.Long.displayName=Длинный

DateFormatType.Short.displayName=Короткий

DateFormatType.Medium.displayName=Средний

DateFormatType.Full.displayName=Полный

DateFormatDetail.Date.displayName=Дата

DateFormatDetail.DateTime.displayName=Дата/Время

ChartUtil.Text.Day='Д'
ChartUtil.Text.Week='Н'
DefaultValueProvider_BaseSeries=Базовый ряд данных

DefaultValueProvider_ChartSubType.Standard=Стандартный

DefaultValueProvider_ChartSubType.StandardMeterChart=Стандартная диаграмма индикатора

DefaultValueProvider_ChartTitle=Заголовок диаграммы

DefaultValueProvider_ChartUnits.Points=Точки

LegendBehaviorType.None.displayName=Нет

LegendBehaviorType.ToggleSerieVisibility.displayName=Переключить видимость ряда данных

LegendBehaviorType.HighlightSerie.displayName=Выделить ряд данных

# Defines cursor display names.
Cursor.Auto.displayName=Автоматически

Cursor.Crosshair.displayName=Перекрестие

Cursor.Default.displayName=По умолчанию

Cursor.Pointer.displayName=Указатель

Cursor.Move.displayName=Перемещение

Cursor.Text.displayName=Текст

Cursor.Wait.displayName=Ожидание

Cursor.EResize.displayName=Восток

Cursor.NEResize.displayName=Северо-восток

Cursor.NWResize.displayName=Северо-запад

Cursor.NResize.displayName=Север

Cursor.SEResize.displayName=Юго-восток

Cursor.SWResize.displayName=Юго-запад

Cursor.SResize.displayName=Юг

Cursor.WResize.displayName=Запад

Cursor.Custom.displayName=Пользовательский

ActionType.URLRedirect.DisplayName=Перенаправление URL

ActionType.InvokeScript.DisplayName=Выполнить скрипт

ActionType.Highlight.DisplayName=Выделить

ActionType.ToggleVisibility.DisplayName=Переключить видимость

ActionType.ToggleDataPointVisibility.DisplayName=Переключить видимость точки данных

# End of Attributes
##################################################
dataprocessor.log.baseSeriesDefn3=Определение ряда категорий ({0}) используется как статическое выражение.

dataprocessor.exception.CannotDecipher=Невозможно расшифровать содержимое диаграммы с несколькими определениями рядов категорий.

dataprocessor.exception.FoundDefnAssociatedWithX=Найдено {0} определений(я) данных, связанных с выражением ряда категорий (X). Поддерживается только одно определение данных ряда категорий.

dataprocessor.exception.DefinitionUnspecified=Не указано определение данных для ряда категорий.

dataprocessor.exception.DefnExpMustAssociateY=Выражение определения данных должно быть связано с рядом значений (Y)-{0}, определённым через {1}.

dataprocessor.exception.AtLeastOneDefnExpMustAssociateY=Как минимум одно выражение определения данных должно быть связано с рядом значений (Y)-{0}, определённым через {1}.

dataprocessor.exception.CannotDecipher2=Невозможно расшифровать содержимое диаграммы с несколькими определениями рядов категорий.

dataprocessor.log.XSeriesDefn=Определение ряда X ({0}) используется как статическое выражение.

dataprocessor.exception.FoundMoreThanOneDefnAssociateX=Найдено {0} определений(я) данных, связанных с выражением ряда (X). Поддерживается только одно определение данных ряда для X.

edataprocessor.xception.definitionsAssociatedWithX=Не указано определение данных для ряда X.

dataprocessor.log.baseSeriesDefnBeStatic=Определение ряда категорий ({0}) используется как статическое выражение.

exception.data.max.row.count=Невозможно отрендерить диаграмму, которая связывает более {0} строк данных.


# Default chart title
BarChart.Title=Заголовок столбчатой диаграммы

LineChart.Title=Заголовок линейной диаграммы

AreaChart.Title=Заголовок диаграммы областей

PieChart.Title=Заголовок круговой диаграммы

MeterChart.Title=Заголовок диаграммы индикатора

ScatterChart.Title=Заголовок точечной диаграммы

StockChart.Title=Заголовок диаграммы котировок

BubbleChart.Title=Заголовок пузырьковой диаграммы

DifferenceChart.Title=Заголовок диаграммы разности

GanttChart.Title=Заголовок диаграммы Ганта

TubeChart.Title=Заголовок трубчатой диаграммы

PyramidChart.Title=Заголовок пирамидальной диаграммы

ConeChart.Title=Заголовок конической диаграммы

RadarChart.Title=Заголовок радарной диаграммы

ColumnChart.Title=Заголовок столбцовой диаграммы

DoughnutChart.Title=Заголовок кольцевой диаграммы