###############################################################################
# Конфигурация плагина
#
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
#
###############################################################################
# Сообщения NLS
#
plugin.name=Дизайнер BIRT Hive
newwizard.name=Источник данных BIRT Hive
newwizard.description=Создать профиль подключения Hive

wizard.window.title=Новый профиль источника данных Hive

wizard.data.source.page.title=Новый источник данных Hive

profile.propertypage.name=Свойства подключения источника данных Hive
dataset.editor.page.query=Запрос HQL
org.eclipse.birt.report.data.oda.hive.ui.ds.displayname=Hive
wizard.data.set.title=Новый набор данных