###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
# 
# Contributors:
# Actuate Corporation - initial API and implementation
###############################################################################
#
MetaData.ProductName=Драйвер POJO ODA

Query.Closed=Запрос закрыт.

Query.NoQueryText=Отсутствует текст запроса.

Query.FailedToParse=Ошибка при анализе запроса POJO: [{0}].

Query.MissAttributeInElement=Атрибут '{0}' пуст или отсутствует в элементе '{1}'.

Query.Miss2Elements=Ни подэлемент '{0}', ни '{1}' не присутствуют в элементе '{2}'.

Driver.UnkownDataTypeCode=Неизвестный код типа данных: {0}.

Driver.UnkownDataTypeName=Неизвестное имя типа данных: {0}.

ResultSet.InvalidAppContextValue=Тип значения AppContext '{0}' равен '{1}', а не массив, итерация или коллекция.

ResultSet.MissDataSetClassName=Отсутствует имя класса набора данных POJO.

PojoDataSetFromCustomerClass.WrongReturnTypeForNextMethod=Недопустимый или примитивный тип возврата метода 'next()'.

ReferenceGraph.DuplicateColumnName=Дублирующееся имя столбца: {0}.

ReferenceGraph.DuplicateColumnIndex=Дублирующийся индекс столбца: {0}.

ReferenceGraph.InexistentColumnName=Несуществующее имя столбца: {0}.

ResultSetFromPojoInstance.Invalid1ToNMaps=Существуют два непостоянных отображения 1-ко-многим.

QueryParameters.OneMethodParameterWith2Types=Параметр метода '{0}' не может иметь 2 типа: '{1}', '{2}'.

QueryParameters.InexistentParameter=Несуществующий параметр: '{0}'.

MethodSource.MissingPrameterValue=Значение параметра '{0}' еще не установлено.

DataTypeUtil.FailToTransferType=Ошибка при преобразовании '{0}' в целевой тип: {1}.

IllegalArgument.errorMessage=Недопустимый аргумент определен для метода: