# ==============================================================================
# Workbench Actions
# ==============================================================================

Workbench_title = Конструктор отчетов BIRT

# --- File Menu ---
Workbench_file = &Файл

Workbench_openFile = &Открыть файл...

Workbench_new = &Создать

Action_newReport = &Новый отчет...

Action_openReport = &Открыть отчет...

# --- Edit Menu ---
Workbench_edit = &Правка

# --- Window Menu ---
Workbench_window = &Окно

Workbench_openPerspective = &Открыть перспективу

Workbench_showView = &Показать вид

Workbench_openNewWindow = &Новое окно

# --- Help Menu ---
Workbench_help = &Справка

Action_newLibrary = Новая &библиотека...

Action_openLibrary = &Открыть библиотеку...

Action_newTemplate = Новый &шаблон...

Action_openTemplate = &Открыть шаблон...

Dialog_openFile = Открыть файл

SaveAsWizardWindowTitle=Сохранить как

SaveAsWizardPageTitle=Сохранить как

SaveAsWizardPageDesc=Сохранить файл в другом месте.

ReportSettingPageTitle=Установить свойства страницы