#************************************************************************
# Copyright (c) 2012 Megha Nidhi Dahal and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#    Megha Nidhi Dahal - initial API and implementation
#    Actuate Corporation - enhanced and refined user messages
#************************************************************************
#
# Сообщения пользователя для драйвера времени выполнения ODA файлов Excel
connection_CONNECTION_PROPERTIES_MISSING=Отсутствуют свойства подключения.
#connection_CANNOT_OPEN_EXCEL_FILE_DB_DIR=Не удалось открыть файл Excel в каталоге:
connection_MISSING_FILELOCATION=Свойство файла источника данных Excel не определено. Требуется путь к файлу или URI для входного файла Excel.

connection_invalidSource=Указан недопустимый или неправильно сформированный URI для файла источника данных Excel.

connection_missingResourceIdentifier=Отсутствует идентификатор ресурса для разрешения относительного пути источника данных Excel:

fileSource_excelFileNotFound=Указанная папка источника данных Excel или файл источника данных Excel ({0}) не найдены.

query_COMMAND_IS_EMPTY=Команда запроса пуста.

query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=Запрос кросс-таблицы не поддерживается.

query_COMMAND_NOT_VALID=Недопустимая информация заголовка в указанном файле Excel.

query_ARGUMENT_ERROR=Аргумент должен быть 'NAME' или 'TYP'.

query_IO_EXCEPTION=Произошло исключение ввода-вывода при чтении файла.

query_SOURCE_DATA_ERROR=Обнаружены дублирующиеся имена столбцов в исходных данных.

query_COLUMN_NAME_ERROR=Ошибка имени столбца

query_INVALID_EXCEL_FILE=Лист не содержит данных. Выберите другой лист.

query_text_error=Ошибка формата в тексте запроса

query_WORKSHEET_CANNOT_BE_NULL=Имя листа не может быть null.

resultSet_COLUMN_NOT_FOUND=Столбец не найден:

resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=Курсор еще не инициализирован.

resultSetMetaData_INVALID_COLUMN_INDEX=Недопустимый индекс столбца:

savedSelectedColumnsInfoString_INVALID=Недопустимая сохраненная информация о столбцах

dataTypes_TYPE_NAME_INVALID=Недопустимое имя типа данных:

dataSetMetaData_PRODUCT_NAME=Поставщик источника данных Excel-ODA

common_ARGUMENT_CANNOT_BE_NULL=Аргументы не могут быть null.

common_CONNECTION_HAS_NOT_OPEN=Подключение не установлено.

common_CANNOT_FIND_COLUMN=Столбцы не найдены.

common_NULL_QUERY_TEXT = Текст запроса равен null

data_read_error=Не удалось корректно прочитать данные. Возможно, были изменены настройки источника данных.

Invalid_column_name = Недопустимое имя столбца

invalid_excelfile_format = Недопустимый формат файла Excel

date_format_null = Формат даты не может быть null.

invalid_date_value = {0} не может быть проанализировано как допустимая дата. Проверьте формат даты в свойствах набора данных.

invalid_sheet_name = Указанный файл не содержит листа с именем {0}.

query_streamClosed=Поток закрыт

query_invalidTableName=Недопустимое имя таблицы:

dateUtil.ConvertFails=Не удалось преобразовать в дату. Источник:

dateFormatISO_cannotConvert=Не удалось преобразовать значение {0}.