###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################


###############################################################################
# General Info
###############################################################################
LibPerspective=Дизайн библиотеки
LibraryEditor=Редактор библиотек

WizardCategoryName=Инструменты бизнес-аналитики и отчетности
LibraryWizard=Библиотека

LibraryWizardDescription=С помощью этого мастера создается новая библиотека.

LibraryProjectWizard=Проект библиотеки

LibraryProjectWizardDescription=Создает новый проект библиотеки.

library.layout=Маке&т

library.script=&Скрипт

library.xmlsource=Исходный файл &XML

design.masterPage=&Master-страница