cheatsheet.category=Инструменты бизнес-аналитики и отчетности
cheatsheet.simplelisting=Отчет с простым списком

cheatsheet.groupedlisting=Отчет со сгруппированным списком

cheatsheet.dualcolumnlisting=Отчет с двухколоночным списком

cheatsheet.chartlisting=Отчет с диаграммой и списком

cheatsheet.sidebysidechartlisting=Отчет с диаграммой и списком бок о бок

cheatsheet.dualcolumnchartlisting=Отчет с двухколоночной диаграммой и списками

cheatsheet.firstreport=Первый отчет

cheatsheet.crosstab=Отчет с кросс-таблицей