###############################################################################
# Конфигурация плагина
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# Строки NLS
dataset.editor.page.query=Запрос

datasource.name=Пример базы данных Classic Models Inc.

select.dataset.name=SQL-запрос выбора

jdbc.driver.name=Драйвер примера БД Classic Models Inc.
dataset.property.queryTimeOut=&Время ожидания запроса (в секундах)

dataset.property.rowFetchSize=Количество &извлекаемых строк
#
oda.data.source.name=Пример базы данных Classic Models Inc.

connection.profile.name=Профиль подключения источника данных примера БД BIRT
#
#  Ниже приведены сообщения NLS, применяемые ко всем источникам данных ODA; должны быть рефакторизованы
#
oda.connection.factory.name=Фабрика подключений ODA