###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Конфигурация плагина
#
oda.data.source.id=org.eclipse.birt.data.oda.mongodb
#
###############################################################################
# Строки NLS
#
plugin.name=Дизайнер ODA источника данных MongoDB
newwizard.name=Источник данных MongoDB
newwizard.description=Создать профиль подключения источника данных MongoDB

wizard.window.title=Новый профиль источника данных MongoDB

wizard.data.source.page.title=Источник данных MongoDB
profile.propertypage.name=Свойства подключения источника данных MongoDB
wizard.data.set.window.title=Новый набор данных MongoDB

wizard.data.set.page.title=Запрос
