#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
# Docx Emitter
DocxEmitter.Description=Настройка параметров рендеринга отчета в формате XML Document 2007.

DocxEmitter.DisplayName=Word (DOCX)

###########################################################
# Значения отображения опций
OptionDisplayValue.ChartDpi=DPI диаграммы

OptionDisplayValue.EmbedHtml=Встроить HTML

###########################################################
# Описания опций
OptionDescription.ChartDpi=DPI для создания диаграмм.

OptionDescription.EmbedHtml=Разрешить использование встроенного HTML в DOCX

###########################################################
# Подсказки
Tooltip.ChartDpi=DPI, используемые движком диаграмм для создания диаграмм. Например, 192.

Tooltip.EmbedHtml=Определяет, следует ли встраивать HTML-содержимое непосредственно в вывод DOCX