###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

About=Инструменты бизнес-аналитики и отчетности
ApplicationName=BIRT Report Designer
ReportPerspective=BIRT Report Designer
CHEAT_SHEETS=Шпаргалки

CHEAT_SHEETS_MENU=&Шпаргалки...

ReportEditor=Редактор отчетов

ReportDocumentEditor=Редактор документов отчетов

LibraryEditor=Редактор библиотек

TemplateEditor=Редактор шаблонов


WizardCategoryName=Инструменты бизнес-аналитики и отчетности
ReportWizard=Отчет

ReportWizardDescription=С помощью этого мастера вы можете создать новый отчет на основе предопределенного шаблона.

TemplateWizard=Шаблон

TemplateWizardDescription=С помощью этого мастера создается новый шаблон.

LibraryWizard=Библиотека

LibraryWizardDescription=С помощью этого мастера создается новая библиотека отчетов.