###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Строки NLS
#
plugin.name=Плагин профиля подключения к примерам баз данных BIRT
connection.profile.name=Пример базы данных BIRT Classic Models
driver.template.name=Встроенный JDBC-драйвер BIRT SampleDb Derby
driver.definition.name=Встроенный драйвер BIRT SampleDb Derby
#
driver.template.property.class =Класс драйвера

driver.template.property.vendor =Поставщик

driver.template.property.version =Версия

driver.template.property.dbname =База данных

driver.template.property.connection.url =URL подключения

driver.template.property.user =Имя пользователя

driver.template.property.password =Пароль

driver.template.property.save.password =Сохранить пароль