SVGRendererImpl.exception.UnableToWriteChartImage=Невозможно записать изображение диаграммы в SVG-дескриптор вывода, определённый через {0}

SVGGraphics2D.drawImage.image=SVG-рендерер – drawImage(Image arg0, AffineTransform arg1, ImageObserver arg2) – не поддерживается

SVGGraphics2D.drawImage.buffer=SVG-рендерер – drawImage(BufferedImage arg0, BufferedImageOp arg1, int arg2, int arg3) – не поддерживается

SVGGraphics2D.drawRenderImage.RenderImage=SVG-рендерер – drawRenderedImage(RenderedImage arg0, AffineTransform arg1) – не поддерживается

SVGGraphics2D.drawRenderableImage.RenderableImage=SVG-рендерер – drawRenderableImage(RenderableImage arg0, AffineTransform arg1) – не поддерживается

SVGGraphics2D.drawString.StringInt=SVG-рендерер – drawString(String arg0, int arg1, int arg2) – не поддерживается

SVGGraphics2D.drawString.StringFloat=SVG-рендерер – drawString(String arg0, float arg1, float arg2) – не поддерживается

SVGGraphics2D.drawString.AttributeInt=SVG-рендерер – drawString(AttributedCharacterIterator arg0, int arg1, int arg2) – не поддерживается

SVGGraphics2D.drawString.AttributeFloat=SVG-рендерер – drawString(AttributedCharacterIterator arg0, float arg1, float arg2) – не поддерживается

SVGGraphics2D.hit.Rectangle=SVG-рендерер – hit(Rectangle arg0, Shape arg1, boolean arg2) – не поддерживается

SVGGraphics2D.getDeviceConfig=SVG-рендерер – GraphicsConfiguration getDeviceConfiguration() – не поддерживается

SVGGraphics2D.setComposite=SVG-рендерер – setComposite(Composite arg0) – не поддерживается

SVGGraphics2D.getRenderingHint.Key=SVG-рендерер – getRenderingHint(Key arg0) – не поддерживается

SVGGraphics2D.setRenderingHints.Map=SVG-рендерер – setRenderingHints(Map arg0) – не поддерживается

SVGGraphics2D.ddRenderingHints.Map=SVG-рендерер – ddRenderingHints(Map arg0) – не поддерживается

SVGGraphics2D.getRenderingHints=SVG-рендерер – getRenderingHints() – не поддерживается

SVGGraphics2D.transform.AffineTransform=SVG-рендерер – transform(AffineTransform arg0) – не поддерживается

SVGGraphics2D.setTransform.Affine=SVG-рендерер – setTransform(AffineTransform arg0) – не поддерживается

SVGGraphics2D.getTransform=SVG-рендерер – AffineTransform getTransform() – не поддерживается

SVGGraphics2D.getComposite=SVG-рендерер – Composite getComposite() – не поддерживается

SVGGraphics2D.setPaintMode=SVG-рендерер – setPaintMode() – не поддерживается

SVGGraphics2D.setXORModel.Color=SVG-рендерер – setXORMode(Color arg0) – не поддерживается

SVGGraphics2D.getFontMetrics.Font=SVG-рендерер – FontMetrics getFontMetrics(Font arg0) – не поддерживается

SVGGraphics2D.CopyArea.Int=SVG-рендерер – copyArea(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5) – не поддерживается

SVGGraphics2D.clearRect.Int=SVG-рендерер – clearRect(int arg0, int arg1, int arg2, int arg3) – не поддерживается

SVGGraphics2D.drawPolyline.Int=SVG-рендерер – drawPolyline(int[] arg0, int[] arg1, int arg2) – не поддерживается