ChartCubeQueryHelper.Error.MustBindCube=Диаграмма должна быть связана с кубом данных для подачи данных.

ChartReportItemPresentationImpl.error.NoData=Набор данных, связанный с диаграммой, не вернул ни одной строки.

ChartReportItemPresentationImpl.error.InvalidCubeBinding=Набор данных, используемый этой диаграммой, был изменён. Данная диаграмма больше не может быть отображена.

ChartReportItemPresentationImpl.log.UnableToLocateWrapper=Не удалось найти обёртку объекта отчёта для объекта диаграммы.

ChartReportItemPresentationImpl.log.onRowSetsStart=ChartReportItemGenerationImpl: onRowSets(...) – Начало

ChartReportItemPresentationImpl.log.onRowSetsBuilding=ChartReportItemPresentationImpl: onRowSets(...) – Создание диаграммы

ChartReportItemPresentationImpl.log.WritingFile=Запись файла {0} в {1}

ChartReportItemPresentationImpl.exception.tmpPngFileCreation=Создание временного PNG-файла

ChartReportItemPresentationImpl.log.PresentationUsesBoundsBo=Презентация использует границы: {0}

ChartReportItemPresentationImpl.log.onRowSetsRendering=ChartReportItemPresentationImpl: onRowSets(...) – Рендеринг диаграммы

ChartReportItemPresentationImpl.exception.inputStreamCreation=Создание входного потока

ChartReportItemPresentationImpl.log.onRowSetsFailed=ChartReportItemPresentationImpl: onRowSets(...) – Ошибка

ChartReportItemPresentationImpl.exception.UnexpectedError=Неожиданная ошибка

ChartReportItemPresentationImpl.onRowSetsEnd=ChartReportItemPresentationImpl: onRowSets(...) – Завершение

ChartReportItemPresentationImpl.log.getSizeStart=ChartReportItemPresentationImpl: getSize(...) – Начало

ChartReportItemPresentationImpl.log.getSizeEnd=ChartReportItemPresentationImpl: getSize(...) – Завершение

ChartReportItemPresentationImpl.log.SuccessfullyDeletedTemp=Временный файл {0} в {1} успешно удалён.

ChartReportItemPresentationImpl.log.finishEnd=ChartReportItemPresentationImpl: finish(...) – Завершение

ChartWithoutAxesImpl.exception.3DNotSupported=3D не поддерживается для диаграмм без осей.

ChartReportItemPresentationImpl.log.finishStart=ChartReportItemPresentationImpl: finish(...) – Начало

ChartReportItemPresentationImpl.log.CouldNotDeleteTemp=Не удалось удалить временный файл {0}, созданный в {1}.

ChartReportItemQueryImpl.log.getReportQueries.exception=ChartReportItemQueryImpl: getReportQueries(...) – Исключение

ChartReportItemQueryImpl.log.getReportQueries.end=ChartReportItemQueryImpl: getReportQueries(...) – Завершение

ChartReportItemQueryImpl.log.getReportQueries.start=ChartReportItemQueryImpl: getReportQueries(...) – Начало

ChartReportItemQueryImpl.exception.getReportQueries=Получение запросов отчёта

ChartReportItemQueryImpl.log.UnableToLocate=Не удалось найти обёртку объекта отчёта для объекта диаграммы.

ChartReportItemImpl.log.validate=Выполняется проверка (...)

ChartReportItemImpl.log.getProperty=getProperty(...) - {0}
ChartReportItemImpl.log.CannotSetState=Невозможно установить состояние 'Транспонировано' для диаграммы без осей.

ChartReportItemImpl.log.UnexpectedChoiceName=Обнаружено неожиданное имя выбора:

ChartReportItemImpl.log.RequestForPropertyDefn=Запрос определений свойств получен до создания модели.

ChartReportItemImpl.log.RequestForScriptPropertyDefn=Запрос определения свойства скрипта

ChartReportItemImpl.log.checkProperty=CheckProperty(...) – {0} со значением {1}

ChartReportItemImpl.log.setProperty=SetProperty(...) – {0} со значением {1}

QueryHelper.exception.UnexpectedNull=Неожиданное 'Null'-определение запроса, предоставленное фреймворком расширений – движок/генерация отчётов.

QueryHelper.Text.CategroySeries=Ряд категорий

QueryHelper.Text.ValueSeries=Ряд значений

QueryHelper.Text.XSeries=Ряд X

QueryHelper.Text.YSeries=Ряд Y

QueryHelper.NoDataDefinitionFor=Отсутствуют записи определения данных для {0}

QueryHelper.dataDefnUndefined=Запись определения данных для {0} не определена.

QueryHelper.InconsitentDataTypesForAxis=Все определения данных на одной оси Y должны иметь одинаковый тип данных.

QueryHelper.InconsitentDataTypesForValueSeries=Все определения данных в рядах значений должны иметь одинаковый тип данных.

ChartElementCommandImpl.editChart=Редактировать диаграмму

ChartElementCommandImpl.setProperty.chart.dimension=Установить измерение

ChartElementCommandImpl.setProperty.chart.instance=Установить модель диаграммы

ChartElementCommandImpl.setProperty.plot.transposed=Установить состояние "Транспонировано"

ChartElementCommandImpl.setProperty.script=Редактировать скрипт диаграммы

ChartElementCommandImpl.setProperty.onRender=Редактировать скрипт диаграммы

ChartImpl.error.DimensionUnitNotSupported=Единица измерения ({0}) не поддерживается в диаграмме "Simple API"

################################################
# Отображаемые имена для расширения модели отчёта
################################################
Element.Chart=Диаграмма

Element.Chart.xmlRepresentation=XML-модель

Element.Chart.outputFormat=Формат вывода

Element.Chart.action=Действие

Element.Chart.altText=Альтернативный текст

Element.Chart.altTextID=Ключ альтернативного текста


choice.chart.dimension.two_dimensional=2D
choice.chart.dimension.two_dimensional_with_depth=2D с глубиной

choice.chart.dimension.three_dimensional=3D
property.category.general=Общие

property.category.types=Типы

property.label.title.value=Заголовок:

property.label.title.font.rotation=Поворот заголовка:

property.label.legend.position=Позиция легенды:

property.label.legend.anchor=Якорь легенды:

property.label.chart.dimension=Измерение:

property.label.chart.plot.transposed=Транспонировано

property.script=Скрипт

property.onRender=onRender

exception.no.cube.edge=Курсор куба данных не имеет края. Проверьте корректность выражений запроса.

exception.script.syntaxError=Синтаксическая ошибка скрипта: {0}