exception.base.orthogonal.null.datadefinition=Указанное выражение определения данных недопустимо.

exception.dataset.stockseries=Привязанные к ряду котировок записи данных неполны. Они должны содержать четыре значения: максимум, минимум, открытие и закрытие.

exception.dataset.null.stockentry=Запись данных содержит недопустимое нулевое значение или значение, не являющееся числом.

exception.dataset.invalid.ganttentry=Запись данных содержит недопустимое значение.

exception.empty.dataset=Обнаружен пустой набор данных

exception.empty.palette=Палитра, связанная с рядом данных {0}, пуста

exception.null.values=Невозможно определить значения 'Все Null' в диаграмме

exception.unknown.datatype=Набор данных, используемый диаграммой, недопустим

exception.dataset.booleantype=Логический тип не разрешён

exception.undefined.riser=Тип подъёма в ряду столбцов {0} не определён

exception.stock.entry.invalid.highlow=Запись котировки недопустима. "Максимум" {0} меньше, чем "Минимум" {1}.

exception.stock.entry.invalid.high=Запись котировки недопустима. "Максимум" {0} меньше, чем "Открытие/Закрытие" {1}.

exception.stock.entry.invalid.low=Запись котировки недопустима. "Минимум" {0} больше, чем "Открытие/Закрытие" {1}.

exception.series.visibility=Видимость для ряда данных {0} не установлена явно

exception.xvalue.scale.bars=Столбцы не могут быть отрендерены на шкале значений

exception.xvalue.scale.lines=Линии не могут быть отрендерены на шкале значений

exception.xvalue.scale.stock=Свечные котировки не могут быть отрендерены на шкале значений

exception.invalid.tick.style.dial=Для ряда данных индикатора указан недопустимый стиль шкалы.

exception.unknown.custom.dataset=Невозможно расшифровать пользовательский набор данных {0}, определённый через {1}

exception.curve.visibility.unset=Для атрибутов линии кривой должна быть установлена видимость

exception.visibility.line.unset=Для атрибутов линии должна быть установлена видимость

exception.cannot.parse.sample=Невозможно проанализировать примерные значения данных, которые должны быть связаны с набором данных ряда

exception.no.stack.percent.3D.chart=Функции стекирования и процентов не поддерживаются в 3D-диаграммах.

exception.dial.dimension="{0}" не поддерживается рядом данных индикатора.

exception.pie.dimension="{0}" не поддерживается рядом данных круговой диаграммы.

exception.scatter.dimension="{0}" не поддерживается рядом данных точечной диаграммы.

exception.stock.dimension=Ряд котировок не может быть отрендерен с измерением {0}

exception.multi.orthogonal.3D.not.supported=3D-диаграммы поддерживают только одну ось значений.

exception.scatter.3D.not.supported=Ось категорий точечной диаграммы не поддерживается 3D-диаграммами.

exception.no.transposed.3D.chart=Транспонирование не поддерживается 3D-диаграммами.

exception.no.transposed.stock.chart=Транспонирование не поддерживается диаграммой котировок.

exception.no.transposed.gantt.chart=Диаграмма Ганта поддерживает только транспонирование.

exception.3D.points.length.less.than.3=Длина списка точек для события рендеринга 3D должна быть не менее 3 (>=3).

exception.empty.icon.list=Список палитр значков для маркеров не содержит элементов.

info.sample.formats=Примеры\nЧисловые: 1,2,3\nДата: 01/26/2005,01/27/2005,01/28/2005\nТекст: 'a,b,c',\nнесколько значений, разделённых запятыми.

info.render.series={0}: renderSeries() [{1}/{2}]
info.stock.sample.format=Пример: H2.30 L4.50 O1.53 C7.01, H5.4 L3.5 O2.9 C6.7

info.datapoint.BubbleValue=Значение пузыря

info.datapoint.BubbleSize=Размер пузыря

info.datapoint.PositiveValue=Положительное значение

info.datapoint.NegativeValue=Отрицательное значение

info.datapoint.GanttStartDate=Дата начала

info.datapoint.GanttEndDate=Дата окончания

info.datapoint.GanttDecorationLabel=Надпись задачи

info.datapoint.High=Максимум

info.datapoint.Low=Минимум

info.datapoint.Open=Открытие

info.datapoint.Close=Закрытие

exception.missing.series.for.palette.index=Ряд данных {0}, необходимый для вычисления индекса палитры, не найден в определении ряда данных {1}

exception.pie.negative.dataset.values=Ряд данных круговой диаграммы не должен содержать отрицательных значений в наборе данных

exception.stock.lineattr.visibility=Атрибуты линии элемента котировки должны быть установлены как видимые

exception.legend.graphic.unknown.riser=Невозможно отрендерить графику легенды для неизвестного типа подъёма {0}

exception.unspecified.visible.series.title=Позиция заголовка ряда данных не установлена для видимого заголовка ряда данных

exception.unspecified.riser.type=Указан неизвестный тип подъёма {0}.

exception.invalid.data.point.position.scatter=Позиция надписи точки данных {0} не поддерживается при рендеринге рядов точечных данных. Допустимые значения: ABOVE, BELOW, LEFT и RIGHT.

exception.invalid.data.point.position.bubble=Позиция надписи точки данных {0} не поддерживается при рендеринге рядов пузырей. Допустимые значения: ABOVE, BELOW, LEFT и RIGHT.

exception.invalid.data.point.outbound.bubble=В области диаграммы нет пузыря. Проверьте шкалу оси.

exception.illegal.pie.series.title.position=Установлено недопустимое значение позиции заголовка = {0} для ряда данных

exception.illegal.datapoint.position.bar=Позиция надписи точки данных {0} не поддерживается при рендеринге рядов столбцов. Допустимые значения: OUTSIDE и INSIDE.

exception.illegal.datapoint.position.line=Позиция надписи точки данных {0} не поддерживается при рендеринге рядов линий. Допустимые значения: ABOVE, BELOW, LEFT и RIGHT

exception.illegal.datapoint.position.stock=Позиция надписи точки данных {0} не поддерживается при рендеринге рядов котировок. Допустимые значения: ABOVE, BELOW, LEFT и RIGHT.

exception.unspecified.datapoint.visibility.pie=Видимость точки данных для ряда данных {0} не установлена

exception.invalid.datapoint.position.pie=Позиция надписи точки данных {0} недопустима

exception.invalid.datapoint.dial=Для отрисовки ряда значений измерения требуется числовая точка данных. Она не должна быть равна нулю.

exception.unspecified.pie.series.title.visibility=Видимость заголовка ряда данных в модели не установлена для {0}

exception.unspecified.marker.linestyle.visibility=Не установлена видимость стиля линии маркера

exception.unsupported.aggregate.function.input=При агрегатной функции {0} обнаружен неподдерживаемый тип данных

exception.illegal.datapoint.position.bar3d=В 3D-столбчатых диаграммах невозможна надпись ряда данных внутри столбцов.

Irr.AggregateFunction.Parameters.Label.Intrate=Внутренняя ставка

Mirr.AggregateFunction.Parameters.Label.FinanceRate=Финансовая ставка

Mirr.AggregateFunction.Parameters.Label.ReinvestmentRate=Ставка реинвестирования

Npv.AggregateFunction.Parameters.Label.Rate=Ставка

Percentile.AggregateFunction.Parameters.Label.Percentage=Процент

Quartile.AggregateFunction.Parameters.Label.Quart=Квартиль

WeightedAverage.AggregateFunction.Parameters.Label.Weight=Вес

MovingAverage.AggregateFunction.Parameters.Label.Window=Окно

RunningNpv.AggregateFunction.Parameters.Label.Rate=Ставка

Rank.AggregateFunction.Parameters.Label.Ascending=По возрастанию

Top.AggregateFunction.Parameters.Label.N=Первые n

TopPercent.AggregateFunction.Parameters.Label.Percentage=Процент

Bottom.AggregateFunction.Parameters.Label.N=Последние n

BottomPercent.AggregateFunction.Parameters.Label.Percentage=Процент

DataSetProcessorImpl_exception.dataset.receivednumeric=Тип полученных данных должен быть числовым.