#************************************************************************
# Copyright (c) 2012 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#************************************************************************
#
# Сообщения пользователя для дизайнера ODA файлов Excel
wizard.defaultMessage.selectExcelFile=Выберите путь или URI файла источника данных Excel или введите его.

wizard.defaultMessage.selectDataSet=Выберите лист и столбцы для набора данных.

connection_CANNOT_OPEN_EXCEL_FILE_DB_DIR=Не удалось открыть файл источника данных Excel в выбранной папке.

ui.ExcelFileNotFound=Указанный файл источника данных Excel не найден.

label.selectFolder=Выбрать &папку:

label.selectFile=Выбрать &файл:

label.selectworksheet=Выбрать &лист:

label.includeTypeLine=Использовать вторую строку как индикатор &типа данных.

label.includeColumnNameLine= Использовать первую строку как индикатор &имен столбцов.

button.selectFolder.browse=О&бзор...

button.moveUp=В&верх

button.moveDown=В&низ

button.delete=Удал&ить

button.selectFileURI.menuItem.relativePath=&Относительный путь

button.selectFileURI.menuItem.absolutePath=&Абсолютный путь

editor.title.name=Имя

editor.title.originalName=Исходное имя

editor.title.type=Тип

datatypes.dateTime=Дата/Время

datatypes.decimal=Decimal

datatypes.float=Число с плавающей точкой

datatypes.integer=Целое число

datatypes.string=Строка

datatypes.date=Дата

datatypes.time=Время

datatypes.boolean=Булево

tooltip.columnnameline=Убедитесь, что первая строка\nвыбранного файла содержит имена столбцов.

tooltip.typeline=Убедитесь, что вторая строка\nвыбранного файла содержит индикатор типа данных.

tooltip.button.add=Добавить все выбранные столбцы из таблицы слева в набор данных для файла Excel.

tooltip.button.up=Переместить выбранный элемент вверх.

tooltip.button.down=Переместить выбранный элемент вниз.

tooltip.button.delete=Удалить выбранный объект.

tooltip.trailNull=Столбцы с нулями в конечной позиции при чтении строк данных.

error.selectFolder=Выберите допустимую папку.

error.selectWorksheet=Выберите лист для набора данных.

error.selectColumns=Выберите хотя бы один столбец для этого набора данных.

error.emptyPath=Введите путь.

error.unexpectedError=Произошла неизвестная ошибка.

error.invalidConnectionFilePath=Указанный исходный путь "{0}" для профиля подключения не существует.

error.errorExist=Ошибка на текущей странице. Все равно сохранить?

error.noFile=Файл источника данных Excel ({0}) не существует.

error.invalidFilePath=Путь к файлу недопустим. Продолжить?

error.emptyFilePath=Путь к файлу пуст. Продолжить?

error.duplicatedNameValueOrEmpty=Дублирующееся значение имени или пустое

error.emptyFolder=В выбранной папке не найден файл источника данных Excel.

title.warning=Предупреждение

warning.fileExtensionInvalid=Выбранный файл может не быть допустимым файлом Excel.

confirm.reselectWorksheetTitle=Подтвердите выбор другого листа.

confirm.reselectWorksheetMessage=При выборе другого листа предыдущие изменения не будут сохранены.\n\nПродолжить?

confirm.reselectFileTitle=Подтвердите выбор другого файла.

confirm.reselectFileMessage=При выборе другого файла предыдущие изменения не будут сохранены.\n\nПродолжить?

RelativeFolderSelectionDialog.Title.SelectFolder=Выберите папку.

RelativeFileSelectionDialog.button.importFile=Импортировать файл...

RelativeFileSelectionDialog.title.error=Ошибка

RelativeFileSelectionDialog.title.overwrite=Перезаписать

RelativeFileSelectionDialog.overwrite.msg=Файл с таким именем уже существует. Перезаписать его?

RelativeFileSelectionDialog.import.msg=Импорт файла...

SelectFile.Title=Выбрать файл