###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=Источник данных XML

oda.xml.dataset=Набор данных XML

oda.xml.tablemapping=Сопоставление таблиц

oda.xml.columnmapping=Сопоставление столбцов


oda.data.source.id=org.eclipse.birt.report.data.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=Дизайнер BIRT ODA XML
oda.data.source.name=Старый источник данных XML 2.1.x

connection.profile.name=Профиль подключения источника данных XML

newwizard.name=Старый источник данных XML BIRT 2.1.x

newwizard.description=Создать профиль подключения источника данных XML 2.1.x

wizard.window.title=Новый профиль источника данных XML

wizard.data.source.page.title=Укажите URL-адреса и информацию о схеме для XML-файла.

profile.propertypage.name=Свойства подключения источника данных XML

preference.datasetpreview=Набор данных XML
#
#  Ниже приведены сообщения NLS, применяемые ко всем источникам данных ODA; должны быть рефакторизованы
#
oda.connection.factory.name=Фабрика подключений ODA