###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

###############################################################################
# General Info
###############################################################################
ReportWizardDescription=С помощью этого мастера создается новый отчет на основе предопределенного шаблона.

ReportProjectWizardDescription=Создать новый проект отчета

ReportPerspective=Дизайн отчета

ReportViews=Дизайн отчета

WizardCategoryName=Инструменты бизнес-аналитики и отчетности
ReportWizard=Отчет

ReportProjectWizard=Проект отчета

ReportEditor=Редактор отчетов


###############################################################################
# UI Framework
###############################################################################
designer.ui.extensionPointName=Отчет с расширенным пользовательским интерфейсом элемента

###############################################################################
# Preference
###############################################################################
preference.birt=Дизайн отчета

preference.datasetpreview=Редактор наборов данных

preference.preview=Предварительный просмотр

preference.preview.server=Сервер предварительного просмотра

preference.elementnames=Имена элементов

preference.library=Библиотека

preference.template=Шаблон

preference.resource=Ресурс

preference.commenttemplates=Шаблон комментария
#hcg_bidi
preference.bidiproperties=Двунаправленные свойства

preference.layout=Макет

preference.expressionsyntax=Синтаксис выражений

designer.action.undo.label=Отменить

designer.action.redo.label=Повторить

extension.odadatasource=Точка расширения источника данных ODA

publish.template=Зарегистрировать шаблон с мастером &нового отчета...

publish.library=&Копировать библиотеку в папку общих ресурсов...

ActionSet.Publish=Публикация ресурсов

Dummy.label=

preference.classpath=Путь к классам

parameter.actions=Новый параметр &отчета