###############################################################################
# Copyright (c) 2010 <<Your Company Name here>>
#
###############################################################################
# Конфигурация плагина
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# Строки NLS
#
plugin.name=Дизайнер ODA источника данных Excel
newwizard.name=Источник данных Excel
newwizard.description=Создать профиль подключения источника данных Excel

wizard.window.title=Новый профиль источника данных Excel

wizard.data.source.page.title=Источник данных Excel
profile.propertypage.name=Свойства подключения источника данных Excel
wizard.data.set.window.title=Новый набор данных Excel

wizard.data.set.page.title=Выбрать столбцы