Templates.jspbirthtml.name=Новый JSP-файл (HTML, тег BIRT)
Templates.jspbirthtml.desc=JSP с HTML-разметкой и тегами BIRT 
Templates.jspbirthtml.content=<%@ page language="java" contentType="text/html; charset=${encoding}"\n    pageEncoding="${encoding}"%>\n<%@ taglib uri="/birt.tld" prefix="birt" %>\n<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=${encoding}">\n<title>Вставьте заголовок здесь</title>\n</head>\n<body>\n${cursor}\n</body>\n</html>

Templates.jspbirttag.name=Taglib JSP (BIRT)
Templates.jspbirttag.desc=Taglib JSP для инструментов отчетности BIRT 
Templates.jspbirttag.content=<%@ taglib uri="/birt.tld" prefix="birt" %>\n