###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

ReportEditor=Редактор отчетов

TemplateEditor=Редактор шаблонов

ReportPerspective=Дизайн отчета

ReportDocumentEditor=Редактор документов отчетов

###############################################################################
# Wizard Info
###############################################################################
WizardCategoryName=Инструменты бизнес-аналитики и отчетности
ReportWizard=Отчет

ReportWizardDescription=С помощью этого мастера создается новый отчет на основе предопределенного шаблона.

TemplateWizard=Шаблон

TemplateWizardDescription=С помощью этого мастера создается новый шаблон.

ReportProjectWizard=Проект отчета

ReportProjectWizardDescription=Создать новый проект отчета

LibraryEditor=Редактор библиотек

LibraryWizard=Библиотека

LibraryWizardDescription=С помощью этого мастера создается новая библиотека отчетов.

OdaRuntimeWizard=Проект plug-in драйвера времени выполнения ODA

OdaRuntimeWizardDesc=Создать новый plug-in драйвера времени выполнения ODA.

OdaDesignerWizard=Проект plug-in для дизайнера ODA

OdaDesignerWizardDesc=Создать новый проект plug-in для дизайнера ODA.

###############################################################################

###############################################################################
# Actions
###############################################################################
Action.Publish=Зарегистрировать шаблон с мастером &нового отчета...

Action.PublishLibrary=&Копировать библиотеку в папку общих ресурсов...

Action.AddReportNature=Добавить поддержку отчета

Menu.Report=Отче&т

birtproblemName=Проблема отчета

###############################################################################
# Preferences
###############################################################################
preference.expressionsyntaxcolor=Цвет синтаксиса выражений