###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Страница конфигурации мастера BIRT
###############################################################################
BIRTProjectCreationWizard_title=Новый веб-проект BIRT

BIRTProjectConfigurationPage_title=Конфигурация BIRT

BIRTProjectConfigurationPage_desc=Настройка параметров, определенных в файле "web.xml", для развертывания BIRT

###############################################################################
# Диалог конфигурации BIRT
###############################################################################
BIRTConfigurationDialog_title=Настройка параметров развертывания BIRT

###############################################################################
# Компоненты конфигурации BIRT
###############################################################################
BIRTConfiguration_group_paths=Настройки папок развертывания

BIRTConfiguration_group_others=Другие настройки

BIRTConfiguration_resource_folder_button_text=О&бзор...

BIRTConfiguration_working_folder_button_text=О&бзор...

BIRTConfiguration_document_folder_button_text=О&бзор...

BIRTConfiguration_image_folder_button_text=О&бзор...

BIRTConfiguration_scriptlib_folder_button_text=О&бзор...

BIRTConfiguration_log_folder_button_text=О&бзор...

BIRTConfiguration_resource_label=Папка &ресурсов:

BIRTConfiguration_resource_dialog_title=Поиск папки ресурсов

BIRTConfiguration_resource_dialog_message=Выберите папку ресурсов по умолчанию:

BIRTConfiguration_working_label=&Рабочая папка:

BIRTConfiguration_working_dialog_title=Поиск рабочей папки

BIRTConfiguration_working_dialog_message=Выберите рабочую папку по умолчанию:

BIRTConfiguration_document_label=Временная папка &документов:

BIRTConfiguration_document_dialog_title=Поиск временной папки документов

BIRTConfiguration_document_dialog_message=Выберите временную папку документов по умолчанию:

BIRTConfiguration_image_label=Временная папка &изображений:

BIRTConfiguration_image_dialog_title=Поиск временной папки изображений

BIRTConfiguration_image_dialog_message=Выберите временную папку изображений по умолчанию:

BIRTConfiguration_scriptlib_label=Папка Script&Lib:

BIRTConfiguration_scriptlib_dialog_title=Поиск папки ScriptLib

BIRTConfiguration_scriptlib_dialog_message=Выберите папку ScriptLib по умолчанию:

BIRTConfiguration_log_label=Папка &журналов:

BIRTConfiguration_log_dialog_title=Поиск папки журналов

BIRTConfiguration_log_dialog_message=Выберите папку журналов по умолчанию:

BIRTConfiguration_report_access_message=Получать доступ &только к отчету и документу в рабочей папке

BIRTConfiguration_overwrite_message=Всегда &перезаписывать созданный файл документа

BIRTConfiguration_maxrows_label=Максимальное количество &строк набора данных:

BIRTConfiguration_maxrowlevels_label=&Максимальные уровни извлекаемых строк для куба:

BIRTConfiguration_maxcolumnlevels_label=Максимальные уровни извлекаемых &столбцов для куба:

BIRTConfiguration_cubememsize_label=Максимальный размер &памяти для создания кубов:

BIRTConfiguration_loglevel_label=Выберите уровень &журналирования:

BIRTConfiguration_loglevel_all=ВСЕ

BIRTConfiguration_loglevel_severe=КРИТИЧЕСКИЙ

BIRTConfiguration_loglevel_warning=ПРЕДУПРЕЖДЕНИЕ

BIRTConfiguration_loglevel_info=ИНФОРМАЦИЯ

BIRTConfiguration_loglevel_config=КОНФИГУРАЦИЯ

BIRTConfiguration_loglevel_fine=ТОЧНЫЙ

BIRTConfiguration_loglevel_finer=БОЛЕЕ ТОЧНЫЙ

BIRTConfiguration_loglevel_finest=НАИБОЛЕЕ ТОЧНЫЙ

BIRTConfiguration_loglevel_off=ВЫКЛ

BIRTConfiguration_printserver_label=&Печатать отчет на сервере:

BIRTConfiguration_import_clear_message=&Удалить старые файлы времени выполнения BIRT.

###############################################################################
# Диалог запроса на перезапись
###############################################################################
BIRTOverwriteQuery_title=Диалог "Перезаписать"

BIRTOverwriteQuery_message=Перезаписать {0}?

BIRTOverwriteQuery_webartifact_title=Диалог "Перезаписать дескриптор развертывания"

BIRTOverwriteQuery_webartifact_message={0} уже существует в файле "web.xml". Перезаписать?

###############################################################################
# Сообщения об ошибках
###############################################################################
BIRTErrors_miss_source=Импорт завершен. Не удалось получить правильную исходную ZIP-файл.

BIRTErrors_wrong_webcontent=Не удалось получить правильную папку веб-контента.