###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Страница конфигурации мастера BIRT
###############################################################################
BIRTProjectCreationWizard_title=Новый веб-проект диаграммы BIRT

###############################################################################
# Диалоговое окно перезаписи запроса
###############################################################################
BIRTOverwriteQuery_title=Диалоговое окно "Перезаписать"

BIRTOverwriteQuery_message=Перезаписать {0}?

BIRTOverwriteQuery_webartifact_title=Диалоговое окно "Перезаписать дескриптор развёртывания"

BIRTOverwriteQuery_webartifact_message={0} уже существует в файле "web.xml". Перезаписать?

###############################################################################
# Сообщения об ошибках
###############################################################################
BIRTErrors_miss_source=Импорт завершён. Не удалось получить правильный исходный ZIP-файл.

BIRTErrors_wrong_webcontent=Не удалось получить правильную папку веб-контента.