JavaxImageIOWriter.exception.no.bounds=Границы изображения должны быть установлены перед началом рендеринга

JavaxImageIOWriter.exception.invalid.image.size=Указанная ширина или высота изображения недопустима (<=0).

JavaxImageIOWriter.exception.no.imagewriter.mimetype.and.format=Не найден зарегистрированный Image Writer для MIME-типа [{0}] и формата [{1}] для {2}

JavaxImageIOWriter.exception.no.imagewriter.mimetype=Не найден зарегистрированный Image Writer для MIME-типа [{0}]

JavaxImageIOWriter.info.using.imagewriter=Используется Image Writer {0} {1}

JavaxImageIOWriter.exception.caption=Исключение:

JavaxImageIOWriter.wrapped.caption=Включено в:

JavaxImageIOWriter.message.caption=Сообщение:

JavaxImageIOWriter.trace.caption=Трассировка:

JavaxImageIOWriter.trace.detail={0}:{1}(...):{2}
Chunk.exception.invalid.png.chunk=Недопустимый тип PNG-чанка: {0}

BmpRendererImpl.exception.unable.write.output.identifier=Невозможно записать изображение диаграммы в дескриптор вывода, определённый через [{0}]

BmpRendererImpl.info.use.custom.image.writer=Для типа изображения [{0}] используется пользовательский Image Writer [{1}]

PngWriter.exception.error.open.fileoutputstream=Ошибка ввода-вывода при открытии FileOutputStream: {0}

PngWriter.exception.error.create.imageproducer=Не удалось создать Producer изображения

PngWriter.error.fail.cleanup.tempfile=Не удалось очистить временный файл [{0}]

PngWriter.error.open.randomaccessfile=Ошибка ввода-вывода при открытии RandomAccessFile: {0}

PngWriter.info.save.elapse.time=Изображение сохранено в {0} [затрачено = {1} мс]

SwingImageCache.exception.media.tracker=MediaTracker вернул ошибку в {0}

SwingImageCache.info.loading.swing.image=Изображение SWING загружается из {0}

SwingImageCache.info.using.swing.cached.image=Используется кэшированное изображение SWING из {0}

SwingImageCache.info.flushed.swing.images=Очищено {0} кэшированное(ых) изображение(ий) SWING

SwingRendererImpl.exception.gradient.angle=Невозможно отрендерить градиент с углом={0}; поддерживаемый диапазон [90 >= 0 >= -90]

SwingRendererImpl.exception.unspecified.text.rendering.action=Отсутствует действие рендеринга текста; TextRenderEvent.setAction(...) не был вызван корректно

SwingRendererImpl.exception.missing.component.interaction=Невозможно активировать интерактивность, если с рендерером не связан IUpdateNotifier

SwingRendererImpl.info.using.graphics.context=Используется графический контекст {0}

SwingTextMetrics.exception.undefined.shadow.color=Невозможно отрендерить тень с неопределённым цветом

SwingTextMetrics.exception.undefined.text.color=Невозможно отрендерить текст с неопределённым цветом

SwingEventHandler.info.toggle.visibility=Переключить видимость: {0}

SwingEventHandler.info.toggle.datapoint.visibility=Переключить видимость точки данных: {0}

SwingEventHandler.info.cannot.find.series=Ряд данных времени разработки не найден для ряда данных времени выполнения: {0}

SwingEventHandler.info.improper.callback.notifier=Обнаружено уведомление: [{0}], но ожидается реализация ICallBackNotifier.

SwingEventHandler.info.redirect.url=Перенаправление на URL: {0}

SwingDisplayServer.info.display.server=Сервер отображения SWING: {0} v{1}