#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
# Excel Emitter
ExcelEmitter.Description=Настройка параметров рендеринга отчета в формате XML Spreadsheet 2003.

ExcelEmitter.DisplayName=Excel (XLS)

###########################################################
# Значения отображения опций
OptionDisplayValue.WrappingText=Включить перенос текста

OptionDisplayValue.OfficeVersion=Версия вывода:

OptionDisplayValue.Office2003=Microsoft Office 2003
OptionDisplayValue.Office2007=Microsoft Office 2007
OptionDisplayValue.ChartDpi=DPI диаграммы

OptionDisplayValue.HideGridlines=Скрыть линии сетки

###########################################################
# Описания опций
OptionDescription.WrappingText=Указывает, содержит ли текст переносы строк.

OptionDescription.ChartDpi=DPI для создания диаграмм.

OptionDescription.HideGridlines=Скрыть линии сетки.

###########################################################
# Подсказки
Tooltip.ChartDpi=DPI, используемые движком диаграмм для создания диаграмм. Например, 192.