#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

########################################
# ReportLauncher
ReportLauncher.PortValueAbsent=Значение порта запроса отсутствует.

ReportLauncher.FailToStartDebugServer=Не удалось запустить сервер отладки.

ReportLauncher.FailToStartReportPlatform=Не удалось запустить платформу отчетов.

ReportLauncher.UserClassPathReceived=Получен пользовательский путь к классам:

ReportLauncher.EngineException=Исключение движка

ReportLauncher.IOException=Исключение ввода-вывода

########################################
# ReportVMClient
ReportVMClient.ServerConnected=[Клиент] Сервер подключен

ReportVMClient.ServerShutDown=[Клиент] Сервер уже остановлен

ReportVMClient.ClientDisconnected=[Клиент] Соединение с клиентом разорвано

ReportVMClient.EnterEventDispatching=[Клиент] начал диспетчеризацию событий

ReportVMClient.ReceivedVMEvent=[Клиент] получил событие VM:

ReportVMClient.ServerShuttingDown=[Клиент] Сервер останавливается

ReportVMClient.RequestIgnored.ServerDisconnected=[Клиент] Соединение с сервером уже разорвано, запрос проигнорирован:

ReportVMClient.RequestIgnored.ServerShuttingDown=[Клиент] Сервер останавливается, запрос проигнорирован:

########################################
# ReportVMServer
ReportVMServer.ClientAccpted=[Сервер] Клиент принят

ReportVMServer.ClientDisconnected=[Сервер] Соединение с клиентом разорвано

ReportVMServer.ServerShutDown=[Сервер] Сервер остановлен

ReportVMServer.EnterRequestDispatching=[Сервер] начал диспетчеризацию запросов

ReportVMServer.ReceivedRequest=[Сервер] получил запрос:

ReportVMServer.SendBackResponse=[Сервер] отправляет ответ

ReportVMServer.ServerShuttingDown=[Сервер] Сервер останавливается

ReportVMServer.SendVMEvent=[Сервер] отправляет событие VM: