###############################################################################
# Copyright (c) 2011 <<Megha Nidhi Dahal>>
#
###############################################################################
# Конфигурация плагина
#
oda.data.source.id=org.eclipse.birt.report.data.oda.excel
#
###############################################################################
# Строки NLS
###############################################################################
#
plugin.name=Драйвер времени выполнения ODA источника данных Excel
data.source.name=Источник данных Excel
data.set.name=Набор данных Excel
connection.profile.name=Профиль подключения источника данных Excel

datasource.property.uri=U&RI
datasource.property.incltypeline=Использовать вторую строку как индикатор &типа данных

datasource.property.inclcolumnnameline=Использовать первую строку как индикатор &имен столбцов

datasource.property.no=НЕТ

datasource.property.yes=ДА

###############################################################################
# Свойства набора данных
datasource.property.excelFile=Выберите файл Excel.

datasource.property.worksheets=&Листы

dataset.property.worksheets.dateFormat=Формат даты
#
###############################################################################
