#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
# Excel Emitter
OdsEmitter.Description=Настройка параметров рендеринга отчета в формате OpenDocument Spreadsheet.

OdsEmitter.DisplayName=OpenDocument Spreadsheet

###########################################################
# Значения отображения опций
OptionDisplayValue.WrappingText=Перенос текста

OptionDisplayValue.ChartDpi=DPI диаграммы

OptionDisplayValue.HideGridlines=Скрыть линии сетки

###########################################################
# Описания опций
OptionDescription.WrappingText=Указывает, содержит ли текст переносы строк.

OptionDescription.ChartDpi=DPI для создания диаграмм.

OptionDescription.HideGridlines=Скрыть линии сетки.

###########################################################
# Подсказки
Tooltip.ChartDpi=DPI, используемые движком диаграмм для создания диаграмм. Например, 192.