#
#************************************************************************
# Copyright (c) 2008, 2009 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
sqbWizPage_cannotOpenConnectionMsg=Не удалось установить подключение для создания SQL-запроса. Проверьте свойства подключения источника данных.

sqbWizPage_cannotOpenConnectionTitle=Ошибка подключения

sqbWizPage_dataSourceDesignError=Ошибка дизайна источника данных

sqbWizPage_dbErrorMsg=Сообщение об ошибке базы данных:

sqbWizPage_defaultMessage=Создать SQL-запрос выбора.

sqbWizPage_detectExternalSqlTextChangedMsg=Текст SQL-запроса был изменен внешне в дизайне набора данных. Хотите заменить содержимое конструктора SQL-запроса этими изменениями?

sqbWizPage_detectSqlTextChangedTitle=Текст SQL-запроса изменен

sqbWizPage_inputFailOnOpenAskUserMessage=Хотите продолжить?

sqbWizPage_invalidSqbStateMsg=Не удалось сбросить конструктор SQL-запроса в предыдущее состояние.

sqbWizPage_invalidSqbStateTitle=Конструктор SQL-запроса - Недопустимое состояние

sqbWizPage_noConnProfileMsg=Профиль подключения к базе данных отсутствует или недопустим. Невозможно открыть конструктор SQL-запроса.

sqbWizPage_connectingDB=Устанавливается подключение к базе данных...

sqbDesignState_invalidSqbStateVersion=Недопустимая версия в сохраненном состоянии конструктора SQL-запроса