###############################################################################
# Конфигурация плагина
oda.data.source.id=org.eclipse.birt.report.data.oda.hive
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# Сообщения NLS

datasource.name=Источник данных Hive
select.dataset.name=HQL-запрос выбора

jdbc.driver.name=Драйвер Hive
dataset.property.queryTimeOut=&Время ожидания запроса (в секундах)

dataset.property.rowFetchSize=&Размер выборки строк

dataset.property.addListFile=&Добавить файл списка
#
oda.data.source.name=Источник данных Hive
connection.profile.name=Профиль подключения источника данных Hive
#
#  Ниже приведены сообщения NLS, применяемые ко всем источникам данных ODA; должны быть рефакторизованы
#
oda.connection.factory.name=Фабрика подключений ODA
