###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Конфигурация плагина
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# Строки NLS
###############################################################################
#
plugin.name=Драйвер времени выполнения ODA источника данных POJO
data.source.name=Источник данных POJO
data.set.name=Набор данных POJO
connection.profile.name=Профиль подключения источника данных POJO
datasource.property.pojoDataSetClassPath=Общее &расположение пользовательских классов наборов данных POJO

datasource.property.pojoClassPath=Общее расположение классов POJO