birt.web.category.name=&Business Intelligence & Reporting Tools

birt.web.project.name=Веб-проект с runtime диаграмм

birt.web.project.description=Создать веб-проект с компонентом диаграммы BIRT

birt.web.actionsets.description=Действия для веб-проекта диаграммы BIRT

create.birt.web.module=Создать веб-модуль диаграммы BIRT

BIRT_FACET_LABEL=Компонент runtime диаграммы BIRT

BIRT_FACET_DESCRIPTION=Компонент runtime диаграммы BIRT

BIRT_FACET_TEMPLATE_LABEL=Веб-проект диаграммы BIRT

BIRT_FACET_TEMPLATE_DESCRIPTION=Веб-проект с компонентом runtime диаграммы BIRT

JSP_New_context_type_Extension_Element.name=Новая JSP с тегом диаграммы BIRT

JSP_Tag_context_type_Extension_Element.name=Новый JSP-тег диаграммы BIRT

birtResourcesDefinition= Определение ресурсов для веб-приложения диаграммы

birt.action.importruntime.name=&Импортировать компонент runtime диаграммы...

##################Do not externalize the version number
runtime.version=4.4.0