#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
connection_nullProfile=Профиль подключения, указанный в свойствах подключения источника данных, не найден.

connection_openFailed=Не удалось открыть подключение с использованием профиля подключения к базе данных.

dBProfileStatement_nullPropertyNameArg=Указан аргумент null для имени свойства в {0}.