SwtRendererImpl.exception.gradient.angle=Невозможно отрендерить градиент с углом={0}; поддерживаемый диапазон [90 >= 0 >= -90]

SwtRendererImpl.exception.unspecified.text.rendering.action=Отсутствует действие рендеринга текста; TextRenderEvent.setAction(...) не был вызван корректно

SwtRendererImpl.exception.missing.component.interaction=Невозможно активировать интерактивность, если с рендерером не связан IUpdateNotifier

SwtRendererImpl.info.graphics.context=Используется графический контекст {0} ({1})

SwtTextRenderer.exception.undefined.shadow.color=Невозможно отрендерить тень с неопределённым цветом

SwtTextRenderer.exception.undefined.text.color=Невозможно отрендерить текст с неопределённым цветом

SwtDisplayServer.exception.display.server=Не удалось получить экземпляр SWTDisplayServer

SwtDisplayServer.info.display.server=Сервер отображения SWT: {0} версия {1}

SwtEventHandler.info.toggle.visibility=Переключить видимость: {0}

SwtEventHandler.info.toggle.datapoint.visibility=Переключить видимость точки данных: {0}

SwtEventHandler.info.cannot.find.series=Ряд данных времени разработки не найден для ряда данных времени выполнения: {0}

SwtEventHandler.info.improper.callback.notifier=Обнаружено уведомление: [{0}], но ожидается реализация ICallBackNotifier.

SwtEventHandler.info.redirect.url=Перенаправление на URL: {0}

R31Enhance.info.advanced.enabled=Расширенные графические функции SWT включены.

R31Enhance.info.advanced.disabled=Расширенные графические функции SWT отключены.