#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
# OpenDocument Text Emitter
OdtEmitter.Description=Настройка параметров рендеринга отчета в формате OpenDocument Text.

OdtEmitter.DisplayName=OpenDocument Text

###########################################################
# Значения отображения опций
OptionDisplayValue.ChartDpi=DPI диаграммы

###########################################################
# Описания опций
OptionDescription.ChartDpi=DPI для создания диаграмм.