# Локализованные сообщения для BIRT. Сообщения здесь содержат
# текст исключений Design Engine.

###########################################################
INVALID_TYPE=Недопустимый тип данных.

INVALID_EXPRSSION=Недопустимое выражение Javascript: {0}

CONVERT_FAILS=Не удалось преобразовать значение "{0}" в тип "{1}".

birt.core.JavascriptCommonError=Ошибка при вычислении скрипта '{0}':\n{1}.

birt.core.JavascriptError={0}
birt.core.Javascript.parameterNotExist=Параметр отчета '{0}' не существует.

birt.core.Javascript.variableNotExist=Переменная отчета '{0}' не существует.

birt.core.Javascript.nativeNotFound={0} не найдено.

birt.core.BirtComp.invalidRegularExpression=Недопустимое регулярное выражение.

error.NoSuchScriptExtension = Расширение скрипта не существует: {0}.

error.InvalidSeekOffset = Недопустимая позиция {0}.

error.ExceedFileLength = Превышена длина файла.

error.CanotchangeReadOnlyBuffer = Нельзя изменить только для чтения буфер.

error.FileOpenedInReadOnlyMode = Файл открыт в режиме только для чтения.

error.FileHasBeenClosed = Файл архива закрыт.

error.UnparseableString = Не удалось проанализировать строковое значение: '{0}'.

error.CannotStartupOSGIPlatform = Не удалось запустить фреймворк OSGI.

error.UnsupportedFileMode = Неподдерживаемый режим файла: {0}.

error.FolderNameIsNull = Ввод имени папки равен Null или пуст.

error.FileNameIsNull = Ввод имени файла равен Null или пуст.

error.NotExt2Archive = Не архив Ext2; магический код: {0}.

error.NotCompoundFile = Не составной файл; магический код: {0}.

error.ReadOnlyArchive = Архив доступен только для чтения.

error.UnsupportedArchiveVersion = Неподдерживаемая версия архива: {0}.

error.UnsupportedBlockSize = Неподдерживаемый размер блока.

error.InvalidIndex = Недопустимый индекс в блоке {0}.

error.UnsupportedNodeType = Неожиданный тип узла: {0} для узла {1}.

error.NotSerializable = Не сериализуется.

error.UnsupportedDataType = Этот тип данных еще не поддерживается или не сериализуется.

error.InvalidLockType = Недопустимый тип блокировки: {0}.

error.ArchiveOpenForWrite = Архив должен быть открыт для записи. Системный ID: {0}.

error.ExceedMaxBlockSize = Размер заголовка архива не должен превышать: {0}.

error.InvalidArchiveName= {0} не существует или не является папкой.

error.NullSource = Исходный архив или целевая папка равны Null.

error.OutOfRange = Позиция поиска находится вне допустимого диапазона.

error.ReadOnlyTree = Невозможно вставить запись в дерево, доступное только для чтения.

error.CannotLoadNode = Не удалось загрузить следующий узел: {0}.

error.KeySizeError = Вместо {1} размер ключа равен {0}.

error.MismatchKeyLength = Длина ключа не соответствует установленной длине ключа.

error.ValueSizeError = Вместо {1} размер значения равен {0}.

error.MismatchValueLength = Длина значения не соответствует установленной длине значения.

error.InvaldMagicTag = Недопустимый магический тег: {0}.

error.UnsupportedVersion = Неподдерживаемая версия: {0}.

error.InvalidCursor = Недопустимый курсор.

error.CusorNotInitialized = Сначала необходимо инициализировать курсор.

error.UnexpectedEqualKeys = Неожиданные одинаковые ключи.

error.UnknownValueType = Неизвестный тип значения: {0}.

error.ExceedMaxBlock = {0} превышает максимальный блок в оперативной памяти {1}.

error.MalformedInputError = Неправильно сформированный ввод: неполный символ в конце.

error.MalformedInputAroundByte = Неправильно сформированный ввод около байта {0}.>>>>>>> 1,8