TasksManager.Exception.RegisterTask=Задача равна "Null" или идентификатор задачи {0} уже существует\!

TasksManager.Exception.DeregisterTask=Задача с идентификатором {0} не зарегистрирована\!

TasksManager.Excepion.RegisterWizard=Идентификатор мастера равен "Null"\!

WizardBase.Excepion.RegisterWizard=Идентификатор задачи {0} не зарегистрирован\!

WizardBase.error.ErrorsEncountered=Возникшие ошибки

WizardBase.Next=Далее >

WizardBase.Back=< Назад

WizardBase.Finish=&Завершить

WizardBase.Cancel=Отмена

WizardBase.error.FollowingErrorsReportedByTask=Завершенное только что окно задачи вернуло следующие ошибки:

WizardBase.error.FollowingErrorEncountered=Возникли следующие ошибки:

WizardBase.error.FollowingErrorsReportedWhileVerifying=При проверке определения диаграммы были обнаружены следующие ошибки:

ErrorDialog.text.ErrorList=Список ошибок:

ErrorDialog.text.ShowDetails=&Показать подробности...

ErrorDialog.text.SuggestedFixes=Предложения по устранению ошибок:

ErrorDialog.text.FixIt=\ \ \ &Исправить

ErrorDialog.text.ProceedWithoutFixing=&Продолжить без исправления ошибок

ErrorDialog.text.Exception=Исключение:

ErrorDialog.text.ShowTrace=Показать трассировку...

ErrorDialog.text.StackTrace=Стек трассировки:

ErrorDialog.text.Ok=\ \ \ \ \ OK

ErrorDialog.text.CausedBy=\n\nПричина:

SubtaskHistory.Tooltip.Back=Назад к {0}

SubtaskHistory.Text.Back=Назад

SubtaskHistory.Tooltip.Forward=Далее к {0}

SubtaskHistory.Text.Forward=Далее

SubtaskHistory.Text.Invalid=\#Недопустимо