###########################################################
#Sample Reports View properties
SampleReportsView.defautDescription=Выберите пример отчета из категорий

SampleReportsView.Text.Explorer=Примеры отчетов

SampleReportsView.Text.Preview=Предварительный просмотр

SampleReportsView.Text.Description=Описание

SampleReportsView.MessageDialog.Title=Вопрос

SampleReportsView.MessageDialog.Message=''{0}'' уже существует. Заменить?

SampleReportsView.Action.exportSampleReport=Сохранить

SampleReportsView.Action.openSampleReport=&Открыть

SampleReportsView.Action.exportSampleReport.toolTipText=Экспортировать выбранный пример отчета

SampleReportsView.Action.openSampleReport.toolTipText.ide=Создать проект отчета и включить отчет в папку проекта

SampleReportsView.Action.openSampleReport.toolTipText.rcp=Экспортировать выбранный пример отчета напрямую в папку рабочей области RCP

SampleReportsView.Text.Contribute_Samples=Добавить примеры

IDEOpenSampleReportAction.ProjectNameDialog.Label.PrjectName=Имя &проекта:

IDEOpenSampleReportAction.ProjectNameDialog.Title.PrjectName=Имя проекта

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Title=Проект уже существует.

IDEOpenSampleReportAction.MessageDialog.ProjectExists.Message=Проект уже существует. Нажмите '{0}' для использования этого проекта, '{1}' для удаления существующего проекта и создания нового, или '{2}' для отмены операции.

IDEOpenSampleReportAction.MessageDialog.ProjectExists.ButtonText=Пере&записать

###########################################################
#NewReportProjectWizard properties

NewReportProjectWizard.bin=bin
NewReportProjectWizard.caseVariantExistsError=В файловой системе не различаются прописные и строчные буквы. Проект с конфликтующим именем ''{0}'' уже существует.

NewReportProjectWizard.description=Создать новый проект отчета

NewReportProjectWizard.errorMessage=При создании нового проекта отчета произошла ошибка.

NewReportProjectWizard.errorOpeningWindow=При открытии окна произошла ошибка.

NewReportProjectWizard.internalError=Внутренняя ошибка: {0}

NewReportProjectWizard.javaProject=Создать Java-проект

NewReportProjectWizard.perspSwitchMessage=Этот тип проекта связан с перспективой {0}. Переключиться на эту перспективу сейчас?

NewReportProjectWizard.perspSwitchTitle=Подтвердить переключение перспективы

NewReportProjectWizard.projectSetting=Настройка проекта

NewReportProjectWizard.src=src
NewReportProjectWizard.title=Проект отчета

NewReportProjectWizard.windowTitle=Новый проект отчета