ChartAggregationCellViewProvider.Chart.DisplayName=Диаграмма

ChartDataSetBindingSheetImpl.Lbl.SelectDataBinding=Выбрать привязку данных:

ChartDataSetBindingSheetImpl.Title.SheetTitle=Данные - Выбрать набор данных

ChartPageGenerator.List.General=Общие

ChartPageGenerator.List.AltText=Альтернативный текст

ChartDataBindingPage.Lbl.Parameter=Параметр

ChartDataBindingPage.Lbl.DataType=Тип данных

ChartDataBindingPage.Lbl.Value=Значение

ChartDataBindingPage.Lbl.None=Нет

ChartDataBindingPage.Lbl.DefaultValue=(Значение по умолчанию)

ChartDataBindingPage.Lbl.DataSet=Набор данных

ChartDataBindingPage.Lbl.SaveParameterBinding=Сохранить привязку параметра

ChartDataBindingPage.Lbl.SaveDataSet=Изменить набор данных

ChartDataBindingPage.Msg.AskSaveDataSet=Вы хотите изменить привязанный набор данных?

DesignerRepresentation.error.Error=Ошибка:

DesignerRepresentation.log.UnableToFind=Не удалось найти модель диаграммы во время рендеринга в дизайнере.

DesignerRepresentation.msg.InvalidChart=Текущая диаграмма недопустима. Если вы хотите продолжить работу с этой диаграммой, сначала необходимо её удалить.

ChartReportItemBuilderImpl.problem.hasNotBeenFound=Диаграмма ещё не связана с набором данных или кубом данных.

ChartReportItemBuilderImpl.log.UnableToLocate=Не удалось найти обёртку объекта отчёта для объекта диаграммы.

ChartPreferencePage.Label.MaxRowNumber=&Максимальное количество строк предварительного просмотра данных:

ChartPreferencePage.Error.MaxRowInvalid=Максимальное количество строк должно быть целым числом и меньше {0}.

ChartPreferencePage.Label.EnableLivePreview=&Включить интерактивный предварительный просмотр в Chart Builder

ChartReportItemUIImpl.Command.ResizeChart=Изменить размер диаграммы

ChartReportItemUIImpl.log.ReceivedNotification=Получена команда на удаление расширенного изображения диаграммы.

ChartReportItemViewProvider.BarChart.Text.Title=Заголовок столбчатой диаграммы:

ChartReportItemViewProvider.ChartViewName=Диаграмма

ChartExpressionProvider.Category.ChartVariables=Переменные

ChartExpressionProvider.ChartVariables.DataPoints=Точка данных диаграммы

ChartExpressionProvider.ChartVariables.LegendItems=Элементы легенды диаграммы

ChartExpressionProvider.DataPoints.BaseValue=Данные категории

ChartExpressionProvider.DataPoints.OrthogonalValue=Данные значений

ChartExpressionProvider.ChartVariables.JavaScript=JavaScript
ChartExpressionProvider.ChartVariables.Event=Событие

ChartExpressionProvider.DataPoints.SeriesValue=Данные ряда данных

ChartColumnBindingDialog.Button.Refresh=Обновить

OpenChartTaskAction.Text.SelectChartType=Выбрать тип диаграммы...

OpenChartTaskAction.Text.SelectData=Выбрать данные...

OpenChartTaskAction.Text.FormatChart=Форматировать диаграмму...

FlipAxisAction.Text.FlipAxis=Инвертировать ось

GeneralPage.Library.Included=Библиотека:

ChartEventHandlerPage.dialog.Browse=Обзор...

ReportDataServiceProvider.Label.DataModel=(Модель данных)

ReportDataServiceProvider.Option.None=<нет>

ReportDataServiceProvider.Option.Inherits=<{0} из контейнера>

ReportDataServiceProvider.Tooltip.Aggregate=Агрегат:

ReportDataServiceProvider.Tooltip.GroupExpression=Выражение группы:

ReportDataServiceProvider.Tooltip.OnGroup=Для группы:

ShowAxisAction.Text.ShowValueAxis=Показать ось значений

StandardChartDataSheet.CheckCubeWarning=Привязки столбцов должны содержать как минимум одно измерение и одну метрику.

StandardChartDataSheet.Combo.DataCubes=---------Кубы данных---------

StandardChartDataSheet.Combo.DataSets=----------Наборы данных----------

StandardChartDataSheet.Combo.InheritColumnsGroups=Наследовать столбцы и группы

StandardChartDataSheet.Combo.InheritColumnsOnly=Наследовать только столбцы

StandardChartDataSheet.Combo.ReportItems=--------Объекты отчёта--------

StandardChartDataSheet.Label.Axis=Ось

StandardChartDataSheet.Label.ToBindADataColumn=Используйте контекстное меню для привязки данных к диаграмме.

StandardChartDataSheet.Label.SelectDataSet=Выбрать данные

StandardChartDataSheet.Label.UseReportData=Наследовать данные из контейнера

StandardChartDataSheet.Label.UseReportItem=Использовать объект отчёта

StandardChartDataSheet.Label.UseDataSet=Использовать данные из

StandardChartDataSheet.Label.DataPreview=Предварительный просмотр данных

StandardChartDataSheet.Label.DataBinding=Привязка данных...

StandardChartDataSheet.Label.Filters=Фильтры...

StandardChartDataSheet.Label.Parameters=Параметры...

StandardChartDataSheet.Task.Description=Выберите данные, которые должны отображаться на диаграмме, и свяжите их с рядом данных.

StandardChartDataSheet.Exception.UnableToSwitchToDataset=Невозможно переключиться на набор данных

StandardChartDataSheet.Label.InsertAggregation=Вставить агрегат

StandardChartDataSheet.Label.DataExpressionBuilder=Построитель выражений данных

StandardChartDataSheet.Label.DragCube=Щёлкните правой кнопкой мыши по уровням или перетащите их на ряд категорий, необязательные Y-ряды или ряды единиц измерения в значения.

StandardChartDataSheet.Label.Component=Компонент

StandardChartDataSheet.Label.CubeTree=Куб данных: Группы и сводные данные

StandardChartDataSheet.Label.Overlay=Наложение

StandardChartDataSheet.Label.Series=Ряд данных

StandardChartDataSheet.Label.ShareCrossTab=В разделе "Ряд значений (Ось Y)" нажмите на кнопку со стрелкой и выберите метрику из списка.

StandardChartDataSheet.Label.ShowDataPreview=Показать предварительный просмотр данных

StandardChartDataSheet.Label.UseAsCategoryXAxis=Использовать как ось категорий (Ось X)

StandardChartDataSheet.Label.UseAsCategorySeries=Использовать как ряд категорий

StandardChartDataSheet.Label.PlotAsValueYSeries=Построить как ряд значений (Ось Y)

StandardChartDataSheet.Label.PlotAsGaugeValue=Построить как значение измерения

StandardChartDataSheet.Label.PlotAsValueSeries=Построить как ряд значений

StandardChartDataSheet.Label.UseToGroupYSeries=Использовать для группировки ряда данных (на оси Y)

StandardChartDataSheet.Label.EnableLivePreview=Включить интерактивный предварительный просмотр диаграммы

StandardChartDataSheet.Label.UseToGroupValueSeries=Использовать для группировки рядов значений

StandardChartDataSheet.Message.RetrieveData=Получить данные для предварительного просмотра

StandardChartDataSheet.NewDataCube=<Новый куб данных...>

StandardChartDataSheet.NewDataSet=<Новый набор данных...>

ChartBindingGroupDescriptorProvider.DataSets.Default=---Наборы данных---

ChartBindingGroupDescriptorProvider.DataCubes.Default=---Кубы данных---

BindingPage.Data.Label=Данные:

BindingPage.ReportItem.NoName=Без имени

Error.ChartShouldIncludeAxes=Диаграмма должна включать оси

ChartCubeFilterConditionBuilder.Expression.CategoryItem.Prefix=Категория:

ChartCubeFilterConditionBuilder.Expression.ValueItemPrefix=Значение:

ChartCubeFilterConditionBuilder.Expression.YOptionItem.Prefix=Y-опция:

ChartCubeFilterConditionBuilder.SelectValueDialog.messages.info.selectVauleUnavailable=Список значений с указанным выражением недоступен.

ChartCubeFilterConditionBuilder.SelectValueDialog.messages.info.illegalVauleExpr=Списки значений, сопоставленные с выражениями, могут быть получены только через выражения в формате 'Данные["Имя"]/[Имя]'.