#/*******************************************************************************
# * Copyright (c) 2013 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
# PPT Emitter
PPTXEmitter.Description=Настройка параметров рендеринга отчета в формате Single File Web Archive (MHTML).

PPTXEmitter.DisplayName=PowerPoint (PPTX)

###########################################################
# Значения отображения опций
OptionDisplayValue.BidiProcessing=Обработка BIDI

OptionDisplayValue.TextWrapping=Перенос текста

OptionDisplayValue.PageOverFlow=Обработка переполнения страницы

OptionDisplayValue.CLIP_CONTENT=Обрезать содержимое

OptionDisplayValue.FIT_TO_PAGE_SIZE=Подогнать под размер страницы

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Вывод на несколько страниц

OptionDisplayValue.ENLARGE_PAGE_SIZE=Увеличить размер страницы

OptionDisplayValue.FontSubstitution=Замена шрифта

OptionDisplayValue.ChartDpi=DPI диаграммы

OptionDisplayValue.RepaginateForPDF=Перенумерация страниц при рендеринге PPTX
OptionDisplayValue.EditMode=Режим редактирования

###########################################################
# Описания опций
OptionDescription.BidiProcessing=Поддерживает двунаправленный текст.

OptionDescription.TextWrapping=Указывает, содержит ли текст переносы строк.

OptionDescription.PageOverFlow=Определяет способ вывода содержимого.

OptionDescription.FontSubstitution=Автоматически выбирает шрифты, если указанный шрифт не может отобразить символ.

OptionDescription.ChartDpi=DPI для создания диаграмм.

OptionDescription.RepaginateForPDF=Перенумерация страниц при рендеринге PPTX.
OptionDescription.EditMode=Редактируемые компоненты в PPTX

###########################################################
# Подсказки
Tooltip.ChartDpi=DPI, используемые движком диаграмм для создания диаграмм. Например, 192.