###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
preference.crosstabPage=Кросс-таблица

crosstab.menu=Кр&осс-таблица

Crosstab.desc=Добавьте кросс-таблицу для отображения агрегированных данных в формате строк/столбцов.

newcube.menu=Новый к&уб данных

paletteEntry.label.crosstab= Кросс-таблица

command.name.createCrosstab= Создать кросс-таблицу

command.name.createCube= Создать куб

command.mnemonic.c=К