#************************************************************************
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
mDbConnection_failedToOpenConn=Не удалось открыть подключение с указанными свойствами.

mDbConnection_invalidDatabaseName=Указанная база данных ({0}) не существует.

mDbConnection_missingValueDBName=Отсутствует обязательное значение в свойстве 'Имя базы данных'.

mDbConnection_noConnection=Отсутствует открытое подключение для подготовки запроса.

mDbDriver_missingValueServerHost=Отсутствует обязательное значение в свойстве 'Хост сервера'.

mDbDriver_nonDefinedDataType=Не определено

mDbDriver_readPrefNearest=ближайший

mDbDriver_readPrefPrimary=основной

mDbDriver_readPrefPrimaryPreferred=предпочтительно основной
mDbDriver_readPrefSecondary=вторичный

mDbDriver_readPrefSecondaryPreferred=предпочтительно вторичный
mDbDSMetaData_dataSourceName=Источник данных MongoDB
mDbMetaData_invalidCollectionName=Недопустимое имя коллекции: {0}

mDbMetaData_missingCmdExprText=Отсутствует выражение для операции команды {0}.

mDbQuery_invalidQueryExecQuery=Запрос недопустим и не может быть выполнен.

mDbQuery_invalidQueryGetMD=Запрос недопустим и не может подготовить результаты метаданных.

driverUtil_invalidExpr=Неожиданный тип выражения: {0}.

driverUtil_parsingError=Ошибка при анализе JSON-выражения: {0}

mDbOp_aggrCmdFailed=Не удалось выполнить операцию агрегатной команды.\nПроверьте, подключен ли сервер MongoDB версии 2.2 или выше.

mDbOp_dbCmdFailed=Не удалось выполнить операцию команды ({0})

mDbOp_invalidQueryExpr=Недопустимое выражение запроса; невозможно выполнить запрос.

mDbOp_mapReduceCmdFailed=Не удалось выполнить операцию команды MapReduce ({0})

mDbOp_noCmdResults=Результаты команды недоступны.

mDbResultSet_cannotConvertFieldData=Не удалось преобразовать значение поля '{0}' ({1}) в тип данных {2} в значение {3}

queryModel_emptyExprErrorMsg=<пустое выражение>

queryModel_invalidCollectionName=Недопустимое имя коллекции (${0}).

queryModel_invalidDbCmdKeyValue=Команда базы данных ({0}) поддерживается только с:\n {1}

queryModel_invalidModelToExec=Недопустимое определение запроса; невозможно выполнить запрос.

queryModel_invalidModelToPrepare=Недопустимое определение запроса; невозможно подготовить запрос.

queryModel_invalidPipelineOp=Недопустимая операция конвейера: {0}

queryModel_invalidQuerySortExpr=Выражение сортировки запроса должно указывать положительное или отрицательное значение для порядка сортировки:\n {0}

queryModel_invalidSortAggrValue=Операция конвейера {0} должна устанавливать значение 1 или -1 в ключе сортировки:\n {1}

queryModel_missingCollectionName=В запросе набора данных не определена коллекция MongoDB.

queryModel_missingGroupAggrKey=Операция конвейера {0} должна устанавливать поле {1}:\n {2}

queryModel_missingMapReduceKey=В выражении команды отсутствует обязательный ключ: {0}

queryModel_missingMapReduceValue=Ключ выражения команды {0} требует значения.

queryModel_missingQueryProps=В наборе данных не определен запрос.

queryModel_nonSupportedDbCmd=Тип команды базы данных не поддерживается:\n {0}

queryProperties_aggrCmdName=Агрегация

queryProperties_dbCmdName=Команда 'Выполнить базу данных'

queryProperties_errDeSerializeDBObject=Не удалось десериализовать выражение MongoDB: {0}

queryProperties_mapReduceCmdName=MapReduce
resultDataHandler_invalidFieldName=Недопустимое имя поля: {0}