#
#************************************************************************
# Copyright (c) 2004, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Сообщения исключений для расширения функций скриптов BIRT
invalid.function.name=Недопустимое имя функции:

invalid.number.of.argument=Недопустимое количество аргументов для функции:

invalid.type.of.argument=Недопустимый тип аргумента для функции:

error.arguement.cannot.empty=Аргумент функции не может быть пустым.

error.incorrect.number.function.fixedArgument=Недопустимое количество аргументов. Ожидаемое количество: <{0}>, фактическое количество: <{1}>.

error.incorrect.number.function.variableArgument=Недопустимое количество аргументов. Ожидаемое количество: максимум <{0}>, фактическое количество: <{1}>.

error.argument.number.outofValidRange=Недопустимое количество аргументов. Ожидаемое количество: минимум <{0}> и максимум <{1}>, фактическое количество: <{2}>.

error.incorrect.type.function.argument=Неправильный тип аргумента.

error.BirtMath.ceiling.significance.notApplied=Указанная значимость '{0}' не может быть применена к числу '{1}'.

error.BirtMath.mod.invalid.divisor=Делитель не может быть равен 0.

error.BirtDateTime.cannotBeNull.DateValue=Значение даты не может быть Null.

error.BirtStr.left.invalidArgument=Значение '{0}' аргумента n недопустимо для функции скрипта.

error.BirtStr.right.invalidArgument=Значение '{0}' аргумента n недопустимо для функции скрипта.

error.BirtStr.indexOf.invalidArgument=Значение '{0}' аргумента начала недопустимо для функции скрипта.

error.BirtStr.search.invalidArgument=Значение '{0}' аргумента начала недопустимо для функции скрипта.

error.BirtDuration.literal.invalidArgument=Значение '{0}' аргумента недопустимо для функции скрипта.