###############################################################################
# Copyright (c) 2005, 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
#Summary aggregates.
Sum.displayName=Сумма

Average.displayName=Среднее

Count.displayName=Количество

DistinctCount.displayName=Уникальное количество

First.displayName=Первое

Last.displayName=Последнее

Min.displayName=Минимум

Max.displayName=Максимум

WeightedAverage.displayName=Взвешенное среднее

Median.displayName=Медиана

Mode.displayName=Мода

STDDEV.displayName=Стандартное отклонение

Variance.displayName=Дисперсия

Irr.displayName=Внутренняя норма доходности

Mirr.displayName=Модифицированная внутренняя норма доходности

NPV.displayName=Чистая приведенная стоимость

Percentile.displayName=Процентиль

Quartile.displayName=Квартиль

#Running aggregates.
MovingAverage.displayName=Скользящее среднее

RunningSum.displayName=Накопительная сумма

RunningNPV.displayName=Накопительная ЧПС

Rank.displayName=Ранг

Top.displayName=В топ-N

TopPercent.displayName=В топ-N-процентов

Bottom.displayName=В низ-N

BottomPercent.displayName=В низ-N-процентов

PercentRank.displayName=Процентный ранг

PercentSum.displayName=Процентная сумма

RunningCount.displayName=Накопительное количество