###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Конфигурация плагина
#
oda.data.source.id=org.eclipse.birt.data.oda.pojo
#
###############################################################################
# Строки NLS
#
plugin.name=Дизайнер ODA источника данных BIRT POJO
newwizard.name=Источник данных BIRT POJO
newwizard.description=Создать профиль подключения для источника данных BIRT POJO

wizard.window.title=Новый профиль источника данных BIRT POJO

wizard.data.source.page.title=Источник данных BIRT POJO
profile.propertypage.name=Свойства подключения источника данных BIRT POJO
wizard.data.set.window.title=Новый набор данных BIRT POJO

wizard.data.set.propertiesPage.title=Свойства

wizard.data.set.columnMappingPage.title=Сопоставление столбцов