###############################################################################
# Copyright (c) 2008, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Конфигурация плагина
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc.dbprofile
parent.category.id=org.eclipse.datatools.connectivity.db.category
#
###############################################################################
# Строки NLS
#
plugin.name=Дизайнер ODA источника данных подключения к базе данных JDBC
newwizard.name=Подключение к базе данных JDBC для конструктора запросов

newwizard.description=Создать профиль подключения для баз данных JDBC

wizard.window.title=Новое подключение к базе данных JDBC для конструктора запросов

wizard.data.source.page.title=Подключение к базе данных JDBC для конструктора запросов

profile.propertypage.name=Драйвер JDBC и детали подключения

wizard.data.set.window.title=Новый SQL-запрос выбора [Редактор запросов]

wizard.data.set.page.title=SQL-запрос выбора