DimensionType.2D=2D
DimensionType.2DWithDepth=2D с глубиной

DimensionType.3D=3D
Shared.Lbl.OK=\ \ \ OK

Shared.Lbl.Cancel=Отмена

ButtonPanel.Lbl.SelectChartType=<< Выбрать тип диаграммы

ButtonPanel.Lbl.Previous=< Назад

ButtonPanel.Lbl.Next=Далее >

ChartAdapter.Info.NotificationRecieved=ChartAdapter: получено уведомление для {0}

ChartAdapter.Info.NewValue=ChartAdapter: новое значение — {0}

ChartSelector.Lbl.ChartSubtypes=Подтипы диаграмм

ChartDlg.Msg.ValidationErrors=При проверке определения диаграммы обнаружены ошибки.\nУстраните эти ошибки перед просмотром отчета.\n\n

ChartDlg.Msg.AskCorrectLater=\nВсе равно закрыть конструктор диаграмм\nи устранить проблемы позже?

ChartDlg.Info.ChartDimension=Размерность:

ChartDlg.Info.AxisOrientation=\tОриентация:

ChartSelector.Lbl.ChartTypes2=Типы диаграмм

ChartSelector.Lbl.DefineChart=Определить диаграмму >>

ChartDlg.Info.AssociatedAxis=\t\tСвязанные оси:

ChartDlg.Info.LineThickness2=\tТолщина линии:

ChartSelector.Lbl.ChartTypes=Типы диаграмм:

ChartSelector.Lbl.Transposed=Транспонировано

ChartAdapter.Exception.Exception=Исключение:

ChartAdapter.Exception.WrappedIn=Включено в:

ChartUIUtil.Exception.NoValueReturned=Значение не возвращено. Укажите допустимый набор данных.

ChartAdapter.Exception.Message=Сообщение:

ChartDlg.Info.CannotChangeSelection=ПРИМЕЧАНИЕ: выбор диаграммы можно изменить только если установлены тип и подтип текущей диаграммы.

ChartAdapter.Exception.Trace=Трассировка:

ChartSelector.Title.ChartSelector=Выбор диаграммы

ChartDlg.Title.ValidationResults=Результаты проверки

ChartDlg.Title.ChartBuilder=Диалог "Диаграмма"

DefaultChartTypeImpl.Label.ValueDefinitionName=Данные значения (&Y)-ряда:

DefaultUIServiceProviderImpl.Warn.Placeholder=DefaultUIServiceProviderImpl: это класс-заглушка без функциональности.

SheetPlaceHolder.Lbl.Placeholder=Это заполнитель для {0}

ChartDlg.Info.ChartStart=--------------------------- Свойства диаграммы - Начало -------------------------

ChartDlg.Info.ChartType=Тип:

ChartDlg.Info.ChartSubType=Подтип:

ChartDlg.Info.Orientation=Ориентация:

ChartDlg.Info.AxisCount=Кол-во осей:

ChartDlg.Info.AxisStart=--------------------------- Информация об осях ----------------------------

ChartDlg.Info.AxisTitle=\tЗаголовок:

ChartDlg.Info.SeriesCount=\tКол-во рядов данных:

ChartDlg.Info.SeriesStart=--------------------------- Информация о рядах данных ----------------------------

ChartDlg.Info.DataSource=\t\tПервый источник:

ChartDlg.Info.SeriesType=\t\tТип ряда данных:

ChartDlg.Info.Riser=\t\tПодъем:

ChartDlg.Info.LineStyle=\t\tСтиль линии:

ChartDlg.Info.Fill=\t\tЗаливка:

ChartDlg.Info.LineStyle2=\t\tСтиль линии:

ChartDlg.Info.Values=\t\tЗначения:

ChartDlg.Info.AxisEnd=--------------------------- Информация об осях ----------------------------

ChartDlg.Info.ChartEnd=--------------------------- Свойства диаграммы - Конец -------------------------

ChartDlg.Info.ChartStart2=--------------------------- Свойства диаграммы - Начало -------------------------

ChartDlg.Info.ChartType2=Тип:

ChartSelector.Lbl.Accept=Принять

ChartWizard.Title.ChartBuilder=Конструктор диаграмм

ChartWizard.Title.NewChart=Новая диаграмма

ChartWizard.Title.EditChart=Редактировать диаграмму

ChartUIUtil.SeriesLabel=Ряд {0}

ChartUIUtil.StockExp.Low=Низкий

ChartUIUtil.Font.Auto=Автоматически

ChartDlg.Info.ChartSubType2=Подтип:

ChartSelector.Lbl.Dimension=&Размерность:

ChartSelector.Lbl.EditChart=Редактировать диаграмму >>

ChartDlg.Info.Dimension=Размерность:

ChartDlg.Info.SeriesCount2=Кол-во рядов данных:

ChartDlg.Info.SeriesStart2=--------------------------- Информация о рядах данных ----------------------------

ChartSelector.Lbl.Subtypes=Подтипы:

ChartUIUtil.StockExp.Close=Закрытие

ChartDlg.Info.DataSource2=\tПервый источник:

ChartDlg.Info.SeriesType2=\tТип ряда данных:

ChartUIUtil.StockExp.High=Высокий

ChartUIUtil.StockExp.Open=Открытие

ChartDlg.Info.Riser2=\tПодъем:

ChartDlg.Info.Values2=\tЗначения:

ChartDlg.Info.ChartEnd2=--------------------------- Свойства диаграммы - Конец -------------------------

PreviewButtonPanel.Lbl.ShowPreview=Пример диаграммы >>

PreviewButtonPanel.Lbl.HidePreview=<< Пример диаграммы

PreviewPanel.Title.Preview=Пример диаграммы

ChartWizard.Label.SelectChartTypeDataFormat=Выберите тип диаграммы, данные и формат.

TaskSelectData.Warning.CategoryGroupTypeCheck=Тип группировки {0} несовместим с типом данных категории ряда данных.

TaskSelectData.Warning.YGroupTypeCheck=Тип группировки {0} несовместим с типом данных группировки рядов данных оси Y.

TaskSelectType.Caption.OverlayAxis1=Заголовок оси Y

ApplyButtonHandler.Label.Apply=&Применить

ChartUIUtil.GanttExp.Label=Метка задачи

ChartUIUtil.GanttExp.Start=Дата начала

ChartUIUtil.GanttExp.End=Дата окончания

ChartUIUtil.BubbleExp.Label=Значение Y

ChartUIUtil.BubbleExp.Size=Размер

ChartUIUtil.DifferenceExp.Postive=Положительный

ChartUIUtil.DifferenceExp.Negative=Отрицательный

ChartUIUtil.TaskSelectData.Warning.CheckAgg.Aggregation=\ агрегат.

ChartUIUtil.TaskSelectData.Warning.CheckAgg.DefaultAggregate=По умолчанию

ChartUIUtil.TaskSelectData.Warning.CheckAgg.GanttChart=Недопустимо для диаграммы Ганта:

ChartUIUtil.TaskSelectData.Warning.CheckAgg.ValueSeriesAggregate=Ряд данных значений

ChartUIUtil.TaskSelectData.Warning.CheckAggAs=\ как

SimpleHyperlinkBuilder.Label.RadioNone=&Без ссылки

SimpleHyperlinkBuilder.Label.RadioURI=&URI
SimpleHyperlinkBuilder.Title=Параметры гиперссылки

SimpleHyperlinkBuilder.Label.SelectType=Выберите тип гиперссылки:

SimpleHyperlinkBuilder.Label.Location=&Расположение:

SimpleHyperlinkBuilder.Label.Target=&Цель:

CustomPreviewTable.Exception.InvalidColumnIndexNotDefined=Недопустимый индекс столбца {0} или столбцы еще не определены\!

CustomPreviewTable.Exception.InvalidColumnIndexSpecified=Указано недопустимое имя столбца\!

CustomPreviewTable.Exception.InvalidColumnIndexSpecifiedOnly=Недопустимый индекс столбца {0}\! Таблица имеет только {1} столбец(ов)\!

CustomPreviewTable.Exception.RowIndexGreaterThan0=Индекс строки должен быть больше или равен 0\!

ExprEditComposite.InvokeExpressionBuilder=Открыть конструктор выражений