datasource.page.title=Определить источник данных для ${odadesignerid.ds.displayname}

datasource.page.msg=Источник данных JDBC, связанный с Hive.

datasource.page.driver.class=Класс драйвера:

datasource.page.url=URL базы данных:

datasource.page.user=Пользователь базы данных:

datasource.upgrade.msg.firstLine=Источник данных ({0}), используемый этим набором данных, был создан в более ранней версии программы.

datasource.upgrade.msg.secondLine=Необходимо обновить определение. \n\nВыберите 'ОК', чтобы обновить источник данных {0} сейчас.

datasource.upgrade.msg.thirdLine=Затем снова откройте редактор набора данных.

datasource.propertyPage.tooltip=Источник данных Hive
datasource.addfile=Команда '&Добавить файл':

datasource.group.text=Сервер Hive
datasource.label.ServerType=&Тип сервера:

datasource.ServerType.type1=HiveServer1
datasource.ServerType.type2=HiveServer2
datasource.error.EmptyURL=URL базы данных не может быть пустым.