#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
# PDF Emitter
PDFEmitter.Description=Настройка параметров рендеринга отчета в формате PDF (Portable Document Format).

PDFEmitter.DisplayName=PDF

###########################################################
# Значения отображения опций
OptionDisplayValue.BidiProcessing=Обработка BIDI

OptionDisplayValue.TextWrapping=Перенос текста

OptionDisplayValue.TextHyphenation=Перенос слов

OptionDisplayValue.PageOverFlow=Обработка переполнения страницы

OptionDisplayValue.CLIP_CONTENT=Обрезать содержимое

OptionDisplayValue.FIT_TO_PAGE_SIZE=Подогнать под размер страницы

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Вывод на несколько страниц

OptionDisplayValue.ENLARGE_PAGE_SIZE=Увеличить размер страницы

OptionDisplayValue.FontSubstitution=Замена шрифта

OptionDisplayValue.EmbeddedFont=Встроенный шрифт

OptionDisplayValue.ChartDpi=DPI диаграммы

OptionDisplayValue.RenderChartInSVG=Рендеринг диаграммы в векторной графике

OptionDisplayValue.RepaginateForPDF=Перенумерация страниц при рендеринге PDF

OptionDisplayValue.DisableFlashAnimation=Отключить Flash-анимацию при печати

OptionDisplayValue.DisablePrint=Отключить печать

###########################################################
# Описания опций
OptionDescription.BidiProcessing=Поддерживает двунаправленный текст.

OptionDescription.TextHyphenation=Поддерживать перенос слов.

OptionDescription.TextWrapping=Указывает, содержит ли текст переносы строк.

OptionDescription.PageOverFlow=Определяет способ вывода содержимого.

OptionDescription.FontSubstitution=Автоматически выбирает шрифты, если указанный шрифт не может отобразить символ.

OptionDescription.EmbeddedFont=Шрифт TrueType встраивается в создаваемый PDF-файл.

OptionDescription.ChartDpi=DPI для создания диаграмм.

OptionDescription.RenderChartInSVG=Рендеринг диаграммы в векторной графике.

OptionDescription.RepaginateForPDF=Перенумерация страниц при рендеринге PDF.

OptionDescription.DisableFlashAnimation=Отключить Flash-анимацию при печати.

OptionDescription.DisablePrint=Отключить печать.

###########################################################
# Подсказки
Tooltip.ChartDpi=DPI, используемые движком диаграмм для создания диаграмм. Например, 192.