###############################################################################
# Copyright (c) 2013 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################
# Сообщения источника данных
DataSource.RuntimeProperty=&Свойства времени выполнения

DataSource.DataSetClassPath=Общее &расположение пользовательских классов наборов данных POJO

DataSource.AddRelativeJars0=&Добавить JAR-файлы (относительный путь)...

DataSource.AddAbsoluteJars0=Добавить JAR-файлы (&абсолютный путь)...

# Чтобы избежать дублирования клавиш быстрого доступа
DataSource.AddRelativeJars1=Добавить JAR-&файлы (относительный путь)...

DataSource.AddAbsoluteJars1=Добавить JAR-файлы (а&бсолютный путь)...

DataSource.AddRelativeClassFolder1=Добавить папку &классов (относительный путь)...

DataSource.AddAbsoluteClassFolder1=Добавить папку классов (абсо&лютный путь)...

DataSource.button.tooltip.AddJar.TwoItems=Добавить JAR-файлы в пути к классам.\nОтносительный путь: путь относительно папки ресурсов.\nАбсолютный путь: абсолютный путь в файловой системе.

DataSource.button.tooltip.AddJar.OneItems=Добавить JAR-файлы в пути к классам.\nАбсолютный путь: абсолютный путь в файловой системе.

DataSource.PojoClassPath=Общее &расположение классов POJO

DataSource.MissDataSetPojoClassPath.runtime=Отсутствует общее расположение пользовательских классов наборов данных POJO, используемых во время выполнения.

DataSource.MissDataSetPojoClassPath.designtime=Отсутствует общее расположение пользовательских классов наборов данных POJO, используемых во время проектирования.

DataSource.PageMessage=Свойства источника данных POJO

DataSource.POJOClasses.tab.runtime=&Свойства времени выполнения

DataSource.POJOClasses.tab.designTime=Свойства &времени проектирования

DataSource.POJOClassTabFolderPage.promptLabel.runtime=Общее &расположение пользовательских классов наборов данных POJO

DataSource.POJOClassTabFolderPage.promptLabel.designtime=Общее &расположение пользовательских классов POJO

DataSource.POJOClassTabFolderPage.button.edit=&Редактировать...

DataSource.POJOClassTabFolderPage.button.up=&Вверх

DataSource.POJOClassTabFolderPage.button.down=&Вниз

DataSource.POJOClassTabFolderPage.button.remove=Удал&ить

DataSource.POJOClassTabFolderPage.menuButton.addJar=Добавить JAR-файлы

DataSource.POJOClassTabFolderPage.menuButton.item.relativePath=Относительный путь

DataSource.POJOClassTabFolderPage.menuButton.item.absolutePath=Абсолютный путь

DataSource.POJOClassTabFolderPage.error.title.empty.resourceIdentifier=Ошибка

DataSource.POJOClassTabFolderPage.error.message.empty.resourceIdentifier=Не удалось получить базовый URI ресурса приложения.

DataSource.ClassPathPage.synchronize.checkbox.message=Использовать свойства времени выполнения для времени выполнения и времени проектирования

DataSource.ClassPathPage.synchronize.checkbox.tooltip=Если эта опция выбрана, редактирование с помощью редактора свойств времени проектирования отключено.

DataSource.ClassPathPage.synchronize.PrompMessage=Примечание: если эта опция выбрана, настройки свойств времени проектирования будут проигнорированы.

DataSource.ClassPathPage.testConnection.failed.runtime=Ошибка при установлении подключения с '{0}' из свойства времени выполнения!

DataSource.ClassPathPage.testConnection.failed.designtime=Ошибка при установлении подключения с '{0}' из свойства времени проектирования!


# Сообщения набора данных
DataSet.PojoDataSetClass=Имя &класса набора данных POJO

DataSet.AppContextKey=&Ключ контекста приложения

DataSet.PojoRootClass=Имя &класса POJO

DataSet.Browse=&Обзор...

DataSet.Browse.tooltip=Поиск класса.

# Чтобы избежать дублирования клавиш быстрого доступа
DataSet.Browse1=О&бзор...

DataSet.DataType.Object=Java-объект

DataSet.FailedParseQueryTitle=Ошибка при анализе текста запроса

DataSet.FailedParseQueryMsg=Текст запроса: '{0}'.

DataSet.FailedToSaveTitle=Ошибка при сохранении набора данных

DataSet.FailedToSaveMsg=Ошибка исключения при сохранении набора данных.

DataSet.Label.MethodNameFilter=&Фильтр имени метода (? = любой символ, * = любая строка):

DataSet.MissPojoRootClass=Не указан класс POJO.

DataSet.Apply=&Применить

DataSet.ClassStructure=Структура класса POJO

DataSet.ColumnMapping=&Сопоставление столбцов

DataSet.Add=&Добавить...

DataSet.Edit=&Редактировать...

DataSet.Remove=&Удалить

DataSet.Up=&Вверх

DataSet.Down=&Вниз

DataSet.Label.POJOClassName=Имя класса POJO

DataSet.Label.prompt.ClassName=Выберите методы и &поля для создания столбцов набора данных.

DataSet.button.addColumn.tooltip.mapColumn=Добавить выбранный элемент как столбец.

DataSet.button.removeColumn.tooltip.mapColumn=Удалить выбранный элемент из таблицы столбцов.

DataSet.button.tooltip.Add=Добавить новый столбец.

DataSet.button.tooltip.Edit=Редактировать текущий столбец.

DataSet.button.tooltip.Remove=Удалить текущий столбец.

DataSet.button.tooltip.Up=Переместить текущий столбец вверх.

DataSet.button.tooltip.Down=Переместить текущий столбец вниз.

DataSet.ShowSampleData=&Показать пример данных

DataSet.button.tooltip.ShowSampleData=Показать пример данных.

DataSet.FailedToLoadClassTitle=Ошибка при загрузке класса.

DataSet.FailedToLoadPojoClassMsg=Ошибка при загрузке класса POJO: '{0}'.

ColumnMappingPage.table.head.columnName=Имя

ColumnMappingPage.table.head.MethodField=Метод/Поле

ColumnMappingPage.table.head.columnType=Тип

ColumnMappingWizardPage.error.getQueryText=Ошибка при анализе исходного текста запроса.

ColumnMappingWizardPage.button.apply.text=&Применить

ColumnMappingWizardPage.button.apply.tooltip=Применить введенные имена классов POJO для создания структуры дерева методов.

ColumnMappingDialog.Label.ColumnName=&Имя столбца:

ColumnMappingDialog.Label.ColumnMethodField=&Метод/Поле:

ColumnMappingDialog.Label.Type=&Тип столбца:

ColumnMappingDialog.table.promptLabel=Выберите &аргументы методов, сопоставленные с параметром:

ColumnMappingDialog.table.head.mapped=Сопоставлено

ColumnMappingDialog.table.head.name=Имя

ColumnMappingDialog.table.head.value=Значение

ColumnMappingDialog.table.head.dataType=Тип данных Java

ColumnMappingDialog.button.edit=&Редактировать...

ColumnMappingDialog.button.selectAll=Выбрать &все

ColumnMappingDialog.button.deselectAll=&Снять выделение

ColumnMappingDialog.Label.methodHierarchy=Иерархия вызовов методов:

ColumnMappingDialog.error.DuplicatedColumnName=Имя столбца уже используется!

ColumnMappingDialog.error.EmptyColumnName=Имя столбца не может быть пустым!

ColumnMappingDialog.error.EmptyMappingPath=Путь сопоставления столбца не может быть пустым!

ColumnMappingDialog.MenuItem.remove=Удалить

ColumnMappingDialog.MenuItem.removeAll=Удалить все

MethodParameterDialog.edit.title=Редактировать параметр метода

MethodParameterDialog.label.name=&Имя:

MethodParameterDialog.label.value=&Значение:

MethodParameterDialog.label.dataType=&Тип данных Java:

MethodParameterDialog.checkBox.message=Установить аргумент, сопоставленный с параметром.

MethodParameterDialog.error.missingName=Для сопоставленного параметра необходимо указать имя!

MethodParameterDialog.error.missingValue=Для параметра константы необходимо указать константное значение!

MethodParameterDialog.error.invalidParamName=Для параметра уже указан другой тип данных!

MethodParameterDialog.error.missingDataType=Тип данных параметра не может быть пустым!

DataSet.DataType.String=Строка

DataSet.DataType.Integer=Целое число
# Сделать метку отображения согласованной с типом данных BIRT
DataSet.DataType.Double=Float

DataSet.DataType.Decimal=Decimal

DataSet.DataType.Date=Дата

DataSet.DataType.Time=Время
# Сделать метку отображения согласованной с типом данных BIRT
DataSet.DataType.Timestamp=Дата/Время

DataSet.DataType.Boolean=Boolean

DataSet.DataType.Blob=Blob

DataSet.AddColumnMapping=Добавить сопоставление столбцов

DataSet.EditColumnMapping=Редактировать сопоставление столбцов

DataSet.InvalidColumnMappingPath=Недопустимый формат метода/поля: '{0}'.

DataSet.InvalidMethodName=Недопустимое имя метода: '{0}'.

DataSet.InvalidFieldName=Недопустимое имя поля: '{0}'.

DataSet.JarsSelectDlg.Title=Выбрать JAR/ZIP-файлы

DataSet.ClassFoldersSelectDlg.Title=Выбрать папки классов

DataSet.PropertyPageMsg=Свойства набора данных POJO

DataSet.ColumnMappingPageMsg=Сопоставление столбцов

DataSet.NoColumnMappingErrorMsg=Отсутствует сопоставление столбцов.

DataSet.ClassNameFilter=&Фильтр имени класса (? = любой символ, * = любая строка):

DataSet.MatchingItems=&Соответствующий элемент:

DataSet.ClassInputDialogTitle=Выбрать класс

DataSet.PreviewDialogTitle=Пример данных

DataSet.FailedFetchSampleData=Ошибка при получении примера данных

ExceptionDialog.title.erro=Ошибка

ExceptionDialog.DataSource.AddDuplicatedJar=Один и тот же JAR-файл нельзя добавить несколько раз.

error.PojoDataSet.emptyClassName=Имя класса не может быть пустым.

JarsSelectionDialog.button.importFile=Импортировать файл...

JarsSelectionDialog.title.error=Ошибка

JarsSelectionDialog.title.overwrite=Перезаписать

JarsSelectionDialog.overwrite.msg=Файл с таким именем уже существует. Перезаписать его?

JarsSelectionDialog.import.msg=Импорт файла...