datasource.page.title=Новый пример источника данных "Classic Models Inc."

datasource.page.msg=Создается источник данных JDBC, связанный с примером базы данных "Classic Models Inc.". Применяются следующие параметры подключения:

datasource.page.driver.class=Класс драйвера:

datasource.page.url=URL базы данных:

datasource.page.user=Пользователь базы данных:

datasource.upgrade.msg.firstLine=Источник данных ({0}), используемый этим набором данных, был создан с более ранней версией этой программы.

datasource.upgrade.msg.secondLine=Определение должно быть обновлено.\n\nВыберите 'OK', чтобы обновить источник данных {0} сейчас.

datasource.upgrade.msg.thirdLine=Затем снова откройте редактор набора данных.

datasource.propertyPage.tooltip=Источник данных JDBC

datasource.page.warning=Внешний профиль подключения не поддерживается для примера базы данных, дизайн изменяется для использования локальных свойств.