###############################################################################
# Preview Framework
###############################################################################
designer.preview.previewtoolbarmenuaction.label=Просмотреть отчет

designer.preview.previewcascadingmenugroup.label=&Просмотреть отчет

document.preview.previewtoolbarmenuaction.label=Просмотреть документ

document.preview.previewmenugroup.label=&Просмотреть документ

ActionSet.Preview=Предварительный просмотр

ActionSet.PreviewWithSecurity=Предварительный просмотр документа

Action.GenDocument=&Создать документ

template.preview=Пред&варительный просмотр

design.preview=Пред&варительный просмотр

preference.preview=Предварительный просмотр

preference.preview.server=Сервер предварительного просмотра

preference.preview.data=Данные

menu.run=&Запустить

###############################################################################
# Actions
###############################################################################
Menu.Report=Отче&т

Action.RunReport=Запустить отче&т

Action.ViewDocument=Показать докуме&нт