ScriptMainTab.title.report=Основная часть

ScriptMainTab.msg.report.file.name=Имя файла отчета

ScriptMainTab.msg.eclipse.home=Корневой каталог Eclipse

ScriptMainTab.msg.engine.home=Корневой каталог движка

ScriptMainTab.msg.temp.folder=Временная папка

ScriptMainTab.msg.debug.type=Тип отладки

ScriptMainTab.msg.task.type=Тип задачи

ScriptMainTab.msg.output=Вывод

ScriptMainTab.msg.format=Формат:

ScriptMainTab.msg.debug.type.all=Все

ScriptMainTab.msg.debug.type.java=Java
ScriptMainTab.msg.debug.type.script=JavaScript
ScriptMainTab.msg.task.type.run.and.render=Выполнение и рендеринг

ScriptMainTab.msg.task.type.run=Выполнение

ScriptMainTab.msg.task.type.render=Рендеринг

ScriptMainTab.msg.task.type.run.plus.render=Выполнение + Рендеринг

ScriptMainTab.error.msg.no.eclipse.home=Корневой каталог Eclipse не указан.

ScriptMainTab.error.msg.nonexist.eclipse.home=Корневой каталог Eclipse не существует.

ScriptMainTab.error.msg.invalid.eclipse.home=Корневой каталог Eclipse должен быть каталогом.

ScriptMainTab.error.msg.no.engine.home=Корневой каталог движка не указан.

ScriptMainTab.error.msg.nonexist.engine.home=Корневой каталог движка не существует.

ScriptMainTab.error.msg.invalid.engine.home=Корневой каталог движка должен быть каталогом.

ScriptMainTab.error.msg.no.temp.folder=Временная папка не указана.

ScriptMainTab.error.msg.nonexist.temp.folder=Временная папка не существует.

ScriptMainTab.error.msg.invalid.temp.folder=Временная папка должна быть каталогом.

ScriptMainTab.error.msg.no.report.file=Файл отчета не указан.

ScriptMainTab.error.msg.nonexist.report.file=Файл отчета не существует.

ScriptMainTab.error.msg.invalid.report.file=Указанный файл не является допустимым файлом дизайна отчета.

ScriptMainTab.error.msg.invalid.document.file=Указанный файл не является допустимым файлом документа отчета.

ScriptMainTab.title.eclipse.home=Корневой каталог Eclipse

ScriptMainTab.msg.select.eclipse.home=Выберите каталог в корневом каталоге Eclipse.

ScriptMainTab.title.temp.folder=Каталог временной папки

ScriptMainTab.msg.select.temp.folder=Выберите каталог в каталоге временной папки.

ScriptMainTab.title.engine.home=Корневой каталог движка

ScriptMainTab.msg.select.engine.home=Выберите каталог в корневом каталоге движка.

ScriptMainTab.msg.select.report.file=Выберите файл отчета.

ScriptMainTab.button.text.search=Поиск...

ScriptMainTab.button.text.variables=Переменные...

ScriptMainTab.msg.open.target.file=Открыть созданный файл после завершения

ScriptMainTab.msg.use.default.engine.home=Использовать корневой каталог движка по умолчанию