#/*******************************************************************************
# * Copyright (c) 2006, 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

report.debug=Отчет BIRT
script.debug=Отчет

LaunchActionSet.label=Отла&дить отчет

Script.source.locator=Поиск исходного кода скрипта отчета

Debug.jsEditor=Отладка редактора JavaScript отчета

javaSourceLocatorName=Поиск исходного кода Java
Watch.label=Добавить в наблюдение

ReportActionSet=Действия с отчетом

Run=&Запустить

ScriptLaunchShortcut.label=Отчет

DebugReportLaunchShortcut.description=Отладка отчета

EnableBreakpoint.label=Включить точку останова

ToggleBreakpoint.label=Включить/выключить точку останова

Action.DebugReport=Отладить отчет

Menu.Report=Отче&т