birt.web.category.name=&Инструменты бизнес-аналитики и отчетности

birt.web.project.name=Веб-проект с компонентом времени выполнения BIRT

birt.web.project.description=Создать веб-проект с компонентом времени выполнения BIRT

birt.web.actionsets.description=Действия для веб-проекта BIRT

create.birt.web.module=Создать веб-модуль BIRT

BIRT_FACET_LABEL=Компонент времени выполнения отчетности BIRT

BIRT_FACET_DESCRIPTION=Компонент времени выполнения отчетности BIRT

BIRT_FACET_TEMPLATE_LABEL=Веб-проект отчетности BIRT

BIRT_FACET_TEMPLATE_DESCRIPTION=Веб-проект с компонентом времени выполнения отчетности BIRT

JSP_New_context_type_Extension_Element.name=Новый JSP с тегом BIRT

JSP_Tag_context_type_Extension_Element.name=Новый тег BIRT-JSP

BirtResourcesDefinition= Определение ресурсов для веб-приложения BIRT

birt.action.importruntime.name=&Импортировать компонент времени выполнения BIRT...


plugin.version=4.4.0