# Локализованные сообщения для oda-jdbc. Сообщения здесь содержат
# текст исключений oda-jdbc.

###########################################################

# Коды ошибок ODA-JDBC
odajdbc.CannotCloseConn=Не удалось закрыть подключение.

odajdbc.ConnCommitError=Произошла ошибка доступа к базе данных, или объект подключения находится в режиме автоматической фиксации.

odajdbc.CannotGetConnMetaData=Не удалось получить метаданные подключения.

odajdbc.CannotGetConn=Не удалось установить подключение.

odajdbc.ConnRollbackError=Ошибка отката подключения.

odajdbc.GetConnectionError=Ошибка при установлении подключения, {0}.

odajdbc.CannotGetMaxStatements=Не удалось получить максимальное количество инструкций из метаданных базы данных.

odajdbc.CannotGetMaxConnections=Не удалось получить максимальное количество подключений из метаданных базы данных.

odajdbc.CannotGetDatabaseMajorVersion=Не удалось получить основную версию базы данных.

odajdbc.CannotGetDatabaseMinorVersion=Не удалось получить дополнительную версию базы данных

odajdbc.CannotGetDataSourceProductName=Не удалось получить имя продукта источника данных.

odajdbc.CannotGetDataSourceProductVersion=Не удалось получить версию продукта источника данных.

odajdbc.CannotGetSQLStateType=Не удалось получить тип состояния SQL.

odajdbc.CannotParseURL=Не удалось проанализировать указанный URL с помощью выбранного драйвера.

odajdbc.CannotParseJNDI=Не удалось проанализировать указанный URL источника данных JNDI с помощью выбранного драйвера.

odajdbc.NoSuitableDriver=Подходящий драйвер не найден.

odajdbc.CannotGetParameterCount=Не удалось получить количество параметров.

odajdbc.CannotGetParameterMode=Не удалось получить режим параметра.

odajdbc.CannotGetParameterType=Не удалось получить тип параметра.

odajdbc.CannotGetParameterTypeName=Не удалось получить имя типа параметра.

odajdbc.CannotGetPrecision=Не удалось получить точность.

odajdbc.CannotGetScale=Не удалось получить масштаб.

odajdbc.CannotDetermineSupportForNull=Не удалось определить, поддерживаются ли нулевые значения для параметра.

odajdbc.CannotGetResultSet=Не удалось получить результат.

odajdbc.CannotGetResultSetMetadata=Не удалось получить метаданные результата.

odajdbc.CannotCloseResultSet=Не удалось закрыть результат.

odajdbc.CursorDownError=Не удалось переместиться к следующей строке в результате.

odajdbc.ResultSetCannotGetStringValue=Не удалось получить значение строки из результата.

odajdbc.ResultSetCannotGetIntValue=Не удалось получить целочисленное значение из результата.

odajdbc.ResultSetCannotGetDoubleValue=Не удалось получить значение Double из результата.

odajdbc.ResultSetCannotGetBigDecimalValue=Не удалось получить значение BigDecimal из результата.

odajdbc.ResultSetCannotGetDateValue=Не удалось получить значение даты из результата.

odajdbc.ResultSetCannotGetTimeValue=Не удалось получить значение времени из результата.

odajdbc.ResultSetCannotGetTimeStampValue=Не удалось получить значение метки времени из результата.

odajdbc.ResultSetCannotGetBlobValue=Не удалось получить значение BLOB из результата.

odajdbc.ResultSetCannotGetClobValue=Не удалось получить значение CLOB из результата.

odajdbc.ResultSetCannotGetBooleanValue=Не удалось получить булево значение из результата.

odajdbc.ResultSetDetermineNull=Не удалось определить значение "isNull" в результате.

odajdbc.ResultSetCannotFindColumn=Столбцы в результате не найдены.

odajdbc.CannotGetColumnCount=Не удалось получить количество столбцов.

odajdbc.CannotGetColumnName=Не удалось получить имя столбца.

odajdbc.CannotGetColumnLabel=Не удалось получить метку столбца.

odajdbc.CannotGetColumnType=Не удалось получить тип столбца.

odajdbc.CannotGetColumnTypeName=Не удалось получить имя типа столбца.

odajdbc.CannotGetColumnDisplaySize=Не удалось получить размер отображения столбца.

odajdbc.CannotGetResultSetMetaDataPrecision=Не удалось получить точность для метаданных результата.

odajdbc.CannotGetResultSetMetaDataScale=Не удалось получить масштаб для метаданных результата.

odajdbc.CannotDetermineColumnSupportForNull=Не удалось определить поддержку нулевых значений для столбца.

odajdbc.StatementCannotPrepared=Ошибка при подготовке SQL-инструкции.

odajdbc.CannotGetMetaData=Не удалось получить метаданные результата.

odajdbc.CannotClosePreparedStatement=Не удалось закрыть подготовленную инструкцию.

odajdbc.CannotGetPreparedStatementMetadata=Не удалось получить метаданные для подготовленной инструкции.

odajdbc.ResultSetCannotReturn=SQL-инструкция не возвращает объект результата.

odajdbc.QueryExecuteFail=SQL-инструкция не возвращает ни объект результата, ни количество обновлений.

odajdbc.InvalidStoredPrecedure=Недопустимая инструкция для вызова хранимой процедуры.

odajdbc.PrepareStatement.CannotSetIntValue=Не удалось установить целочисленное значение параметра для подготовленной инструкции.

odajdbc.PrepareStatement.CannotSetDoubleValue=Не удалось установить значение Double параметра для подготовленной инструкции.

odajdbc.PrepareStatement.CannotSetBigDecimalValue=Не удалось установить значение BigDecimal параметра для подготовленной инструкции.

odajdbc.PrepareStatement.CannotSetStringValue=Не удалось установить строковое значение параметра для подготовленной инструкции.

odajdbc.PrepareStatement.CannotSetDateValue=Не удалось установить значение даты параметра для подготовленной инструкции.

odajdbc.PrepareStatement.CannotSetTimeValue=Не удалось установить значение времени параметра для подготовленной инструкции.

odajdbc.PrepareStatement.CannotSetTimestampValue=Не удалось установить значение метки времени параметра для подготовленной инструкции.

odajdbc.PrepareStatement.CannotSetBooleanValue=Не удалось установить булево значение для подготовленной инструкции.

odajdbc.PrepareStatement.CannotSetNullValue=Не удалось установить значение Null для подготовленной инструкции.

odajdbc.PrepareStatement.CannotGetParameterType=Не удалось получить тип параметра из метаданных параметра.

odajdbc.CannotGetParameterMetadata=Не удалось получить метаданные параметра.

odajdbc.ClearParametersError=Ошибка при очистке текущего значения параметра.

odajdbc.missedUrlAndJndi=GetConnection: и url, и jndiNameUrl имеют значение 'Null'.

odajdbc.error.emptyDriverClass=GetConnection: имя класса драйвера имеет значение 'Null'.

# используется в ошибках assert
odajdbc.driver.ConnNotOpen=Подключение не установлено.

odajdbc.driver.DriverMissingProperties=Отсутствуют свойства в Connection.open(Properties).

odajdbc.driver.ParameterMetadataCannotNull=ParameterMetaData не может быть равен Null.

odajdbc.driver.ResultSetCannotNull=ResultSet не может быть равен Null.

odajdbc.driver.ResultSetMetadataCannotNull=ResultSetMetaData не может быть равен Null.

odajdbc.driver.StatementCannotNull=Инструкция должна быть подготовлена для этой операции.

odajdbc.CannotGetMaxQueries=Не удалось получить MaxStatements из основного JDBC-подключения.

odajdbc.CannotSetQueryTimeout=Не удалось установить время ожидания запроса для основного JDBC-подключения.

odajdbc.BadQueryProperty=Свойство запроса не поддерживается: {0}.

odajdbc.CannotLoadDriverClass=Не удалось загрузить класс JDBC-драйвера: {0}.

odajdbc.CannotInstantiateDriverClass=Не удалось создать экземпляр класса JDBC-драйвера: {0}.

odajdbc.CannotInstantiateFactory=Не удалось создать экземпляр класса фабрики подключений "{0}", определенный в расширении для класса драйвера "{1}".

odajdbc.jndi.InvalidJndiResource=Найден тип ресурса JNDI ({0}); ожидается тип javax.sql.DataSource.

odajdbc.testfail=Тест не пройден