Connection.PropertiesMissing=Некоторые свойства подключения отсутствуют.

Connection.InvalidAppContext=Недопустимый AppContext.

Constants.DriverName=Драйвер ODA-XML

ResultSet.ResultSetClosed=Результат закрыт.

Query.QueryHasNotBeenPrepared=Запрос еще не подготовлен.

Query.ResultSetClosed=Результат закрыт.

Query.InvalidQueryText=Текст запроса недопустим.

RelationInformation.InputStringCannotBeNull=Входная строка не может быть пустой или равной null.

RelationInformation.InvalidDataTypeName=Указанное имя типа данных недопустимо.

DateUtil.ConvertFails=Не удалось преобразовать в дату. Источник: