preference.description = Двунаправленный формат по умолчанию для источника данных JDBC

preference.bidiframe.title = Двунаправленный формат

preference.bidiframe.arabictitle = Специальные функции для арабского языка

report.bidi.properties.externalbidiformat.orderingscheme.metadata=&Схема сортировки

report.bidi.properties.externalbidiformat.orderingscheme.content=С&хема сортировки

report.bidi.properties.externalbidiformat.shaping.metadata=&Форма текста

report.bidi.properties.externalbidiformat.shaping.content=Форма &текста

report.bidi.properties.externalbidiformat.numshaping.metadata=&Числовая форма

report.bidi.properties.externalbidiformat.numshaping.content=Ч&исловая форма

report.bidi.properties.externalbidiformat.symswap.metadata=&Симметричное зеркальное отображение

report.bidi.properties.externalbidiformat.symswap.content=Симметричное з&еркальное отображение

report.bidi.properties.externalbidiformat.textdirection.metadata=&Направление текста

report.bidi.properties.externalbidiformat.textdirection.content=На&правление текста

report.bidi.properties.externalbidiformat.orderingscheme.tooltip = Выбрать значение для схемы сортировки

report.bidi.properties.externalbidiformat.textdirection.tooltip = Выбрать значение для направления текста

report.bidi.properties.externalbidiformat.symswap.tooltip = Выбрать значение для симметричного зеркального отображения

report.bidi.properties.externalbidiformat.symswap.true=Истина

report.bidi.properties.externalbidiformat.symswap.false=Ложь

report.bidi.properties.externalbidiformat.shaping.tooltip = Выбрать значение для формы текста

report.bidi.properties.externalbidiformat.numshaping.tooltip = Выбрать числовую форму

report.bidi.properties.externalbidiformat.orderingscheme.visual =Визуальная

report.bidi.properties.externalbidiformat.orderingscheme.logical =Логическая

report.bidi.properties.externalbidiformat.textdirection.ltr=Слева направо

report.bidi.properties.externalbidiformat.textdirection.rtl=Справа налево

report.bidi.properties.externalbidiformat.textdirection.contextltr=Контекстно слева направо

report.bidi.properties.externalbidiformat.textdirection.contextrtl=Контекстно справа налево

report.bidi.properties.externalbidiformat.shaping.shaped=Формированный

report.bidi.properties.externalbidiformat.shaping.nominal=Номинальный

report.bidi.properties.externalbidiformat.numshaping.national=Национальный

report.bidi.properties.externalbidiformat.numshaping.nominal=Номинальный

report.bidi.properties.externalbidiformat.numshaping.contextual=Контекстный

report.bidi.properties.externalbidiformat = Внешний двунаправленный формат

report.bidi.properties.nonbididirection = Слева направо

advancedbididialog.title=Расширенные настройки для двунаправленных источников данных

advancedbididialog.msg=Установить двунаправленные форматы для метаданных и содержимого

advancedbidi.button=Двунаправленные настройки...

metadata.bidiframe.title=Двунаправленный формат метаданных от внешней системы

content.bidiframe.title=Двунаправленный формат содержимого от внешней системы

disablebidi.checkbox.label=&Отключить двунаправленную трансформацию