###########################################################
# Свойства узла дерева Cube
DefaultNodeProvider.Tree.Cubes=Кубы

cube.new=Новый куб

cube.action.new=Новый к&уб данных

cube.edit=Редактировать куб

CubeNodeProvider.menu.text=&Редактировать

cube.dimension.new=Новое измерение куба

cube.dimension.edit=Редактировать измерение куба

CubeDimensionNodeProvider.menu.text=&Редактировать

CubeGroupContent.Message.Add.Message=Имя сводного поля:

CubeGroupContent.Group.Edit.Message=Имя группы:

CubeGroupContent.Measure.Edit.Title=Редактировать сводное поле

cube.level.new=Новый уровень куба

cube.level.edit=Редактировать уровень

CubeLabelProvider.SharedDimensions=Общие измерения

CubeLevelNodeProvider.menu.text=&Редактировать

cube.measure.new=Новая единица измерения куба

cube.measure.edit=Редактировать единицу измерения куба

CubeMeasureNodeProvider.menu.text=&Редактировать

CubeGroupContent.Group.Add.Title=Добавить группу

CubeGroupContent.Group.Add.Message=&Имя группы:

CubeGroupContent.Measure.Add.Title=Добавить сводное поле

CubeGroupContent.Group.Edit.Title=Редактировать группу

cube.measuregroup.new=Новая группа единиц измерения куба

cube.measuregroup.edit=Редактировать группу единиц измерения куба

CubeMeasureGroupNodeProvider.menu.text=&Редактировать

CubeGroupContent.Measure.Edit.Message=Имя сводного поля:

CubeModel.group.edit=&Редактировать группу

Cube.Other.Datasets=Другие

CubeModel.summaryfield.edit=&Редактировать сводное поле

Cube.Groups=Группы (измерения)

Cube.MeasureGroup=Сводные поля (единицы измерения)

CubeGroupContent.MeasureDataTypeErrorDialog.Message=Единица измерения не поддерживает тип данных "Любой". Выберите другой столбец данных или измените тип данных столбца "{0}".

CubeGroupContent.MeasureDataTypeErrorDialog.Title=Предупреждение
###########################################################
# Свойства диалога Cube Builder
CubeBuilder.AutoPrimaryKeyDialog.Message=Некоторые столбцы, используемые в качестве ключей связи, не определены на уровнях. Хотите проверить опцию 'Автоматический первичный ключ' для завершения куба?

CubeBuilder.AutoPrimaryKeyDialog.Title=Проблема с автоматическим первичным ключом

CubeBuilder.SharedDimensionErrorLinkDialog.Message=Все первичные ключи из общих измерений должны быть связаны между собой. Хотите указать отсутствующие связи для завершения куба?

CubeBuilder.SharedDimensionErrorLinkDialog.Title=Отсутствует связь общего измерения

CubeBuilder.Title=Создание куба данных

DatasePage.EmptyName.ErrorMessage=Имя куба обязательно.

DatasetPage.Title=Набор данных

GroupDialog.Access.Control.List.Expression=&Выражение списка управления доступом:

GroupDialog.Button.DateGroup=&Группа дат

GroupDialog.Button.RegularGroup=&Обычная группа

GroupRenameDialog.Access.Control.List.Expression=&Выражение списка управления доступом:

GroupsPage.Title=Группы и сводные данные

LinkGroupsPage.Title=Связать группы

DatasetPage.Label.Name=&Имя:

DateGroupDialog.Title=Добавить/редактировать уровень группы

DateGroupDialog.Message.NumericName=Имя группы не может быть только числом.

DateGroupDialog.Message.DuplicateName=Имя уже используется.

DateGroupDialog.Message.BlankName=Имя группы не может быть пустым.

DateLevelDialog.Access.Control.List.Expression=&Выражение списка управления доступом:

DateLevelDialog.Button.Text.Edit=&Редактировать...

DateLevelDialog.Title=Редактировать уровень даты

DatasetPage.Label.PrimaryDataset=&Первичный набор данных:

DatasetPage.Button.Filter=&Фильтр...

DatasetPage.Button.Joint=Добавить связанный набор данных...

DatasetPage.Title.Title=Набор данных

DateGroupDialog.Message=Выберите поля дат для включения.

DateGroupDialog.Message.Regular=Введите имя группы.

DateLevelDialog.Message=Редактировать уровень типа даты

DateLevelDialog.Message.NumericName=Имя уровня не может быть только числом.

DateLevelDialog.Message.BlankName=Имя уровня не может быть пустым.

DatasetPage.Title.Message=Определить набор данных для куба.

DatasetPage.Container.Title.Message=Выбор набора данных

DatasetNodeEditPart.Primary.Dataset=(Первичный)

GroupsPage.Title.Title=Группы и сводные данные

GroupsPage.Title.Message=Перетащите поля из доступных наборов данных в иерархии группировки и поля сводных данных.

GroupsPage.Container.Title.Message=Группы и сводные данные

SimpleCubeBuilder.Title.Title=Конструктор куба для кросс-таблицы

SimpleCubeBuilder.Title.Message=Управляйте данными для кросс-таблицы, указывая иерархии группировки и поля сводных данных.

SimpleCubeBuilder.Title=Конструктор куба для кросс-таблицы

SimpleCubeBuilder.Label.Name=Имя:

DatasetSelectionPage.Label.Auto.Primary.Key=&Выберите эту опцию, чтобы избежать предварительной агрегации в первичном наборе данных при создании куба.

DatasetSelectionPage.Text.Auto.Primary.Key=Примечание. Если эта опция включена, BIRT пропускает вычисления группировки и агрегации при создании куба для достижения лучшей производительности.

DatasetSelectionPage.Combo.NewDataSet0=<Новый набор данных...>

GroupsPage.Button.Add=&Добавить

GroupsPage.Button.Edit=&Редактировать

GroupsPage.Button.Delete=&Удалить...

GroupsPage.ArrowButton.Add.Tooltip=Добавить выбранное поле

GroupsPage.ArrowButton.Remove.Tooltip=Удалить выбранное поле

GroupsPage.Label.DataField=Доступные поля:

GroupsPage.Label.Group=Группы и сводные данные:

GroupsPage.tooltip.Sort=Сортировать

GroupsPage.Primary.Dataset=(Первичный)

GroupsPage.VirtualField.Measure=(Перетащите поле сюда для создания единицы измерения)

GroupsPage.VirtualField.Level=(Перетащите поле сюда для создания уровня)

GroupsPage.VirtualField.MeasureGroup=(Перетащите поле сюда для создания сводного поля)

GroupsPage.VirtualField.Dimension=(Перетащите поле сюда для создания группы)

GroupsPage.Reference=Найдена ссылка

GroupsPage.Clients=\ имеет следующих клиентов

GroupsPage.Dlg.Confirm=Вы действительно хотите удалить элемент?

LinkGroupsPage.Container.Title.Message=Связать группы

LinkGroupsPage.Title.Title=Связать группы

LinkGroupsPage.Title.Message=Чтобы связать группу из другого набора данных с первичным набором данных, перетащите поле из группы на поле в первичном наборе данных.

LevelDialog.Title=Свойство

LevelDialog.Label.Name=Имя:

LevelDialog.Label.Field=Выберите поле:

LevelDialog.Label.DataType=Тип данных:

LevelDialog.Label.Info=Выбранный ключ:

LevelDialog.Label.Add=Добавить уровень группы

LevelDialog.Label.Edit=Редактировать уровень группы

LevelDynamicAttributeDialog.Label.Member=&Элемент:

MeasureDialog.Access.Control.List.Expression=&Выражение списка управления доступом:

MeasureDialog.Button.Text.Edit=&Редактировать...

MeasureDialog.Title=Свойства

MeasureDialog.Label.Name=&Имя:

MeasureDialog.Label.DisplayName=Отобража&емое имя:

MeasureDialog.Label.Function=&Функция:

MeasureDialog.Label.DataType=&Тип данных:

MeasureDialog.Label.Expression=В&ыражение:

MeasureDialog.Label.LinkTo=&Связать с:

MeasureDialog.MessageDialog.Message=Рекомендуемый тип данных для текущей функции — '{0}'. Вы действительно хотите сохранить выбранный тип данных?

MeasureDialog.MessageDialog.Title=Предупреждение

MeasureDialog.Title.Property=Редактировать сводное поле

MeasureDialog.Title.Description=Сводное поле

MeasureDialog.Text.Description=Для редактирования сводного поля укажите сводную функцию и выражение, использующее поля данных.

MeasureDialog.Message.NumericName=Имя не может быть только числом.

MeasureDialog.Message.BlankName=Имя единицы измерения не может быть пустым.

MeasureDialog.Message.BlankExpression=Выражение не может быть пустым

MeasureDialog.Label.DerivedMeasure=&Является вычисляемой единицей измерения

MeasureDialog.Label.ExprDesc=например, dataSetRow["QUANTITYORDERED"]

MeasureDialog.Label.ExprDesc.Derived=например, measure["QuantityOrdered"] * measure["PriceEach"]

MeasureDialog.Label.Visibility=&Скрыть единицу измерения

MeasureDialog.Label.Visibility.Group=Видимость

LevelPropertyDialog.Access.Control.List.Expression=&Выражение списка управления доступом:

LevelPropertyDialog.Title.Add=Добавить уровень группы

LevelPropertyDialog.Title.Edit=Редактировать уровень группы

LevelPropertyDialog.Member.Access.Control.List.Expression=&Выражение списка управления доступом для элемента:

LevelPropertyDialog.Message=Определите уровень группы как динамический или статический и заполните необходимые поля

LevelPropertyDialog.Message.NumericName=Имя свойства не может быть только числом.

LevelPropertyDialog.Message.BlankName=Имя свойства не может быть пустым.

LevelPropertyDialog.Message.BlankKeyField=Поле ключа не может быть пустым

LevelPropertyDialog.Message.BlankDataType=Поле типа данных не может быть пустым

LevelPropertyDialog.None=Нет

LevelPropertyDialog.GroupBy=Группировать по:

LevelPropertyDialog.Name=&Имя:

LevelPropertyDialog.MSG.Static.CreateNew=<Создать новый элемент>

LevelPropertyDialog.Shell.Title=Уровень группы

LevelPropertyDialog.StaticAttributeDialog.Title.Edit=Редактировать атрибут уровня

LevelPropertyDialog.StaticAttributeDialog.Title.New=Новый атрибут уровня

LevelPropertyDialog.StaticTable.Button.Add=&Добавить...

LevelPropertyDialog.StaticTable.Button.Edit=&Редактировать...

LevelPropertyDialog.StaticTable.Button.Remove=&Удалить

LevelPropertyDialog.Button.Dynamic=Д&инамический

LevelPropertyDialog.Button.Static=&Статический

LevelPropertyDialog.DisplayField=&Поле отображения:

LevelPropertyDialog.Button.None=Нет

LevelPropertyDialog.Button.Prefix=Префикс

LevelPropertyDialog.Button.Text.Edit=&Редактировать...

LevelPropertyDialog.Interval.Base=Использовать фиксированное базовое значение для интервала:

LevelPropertyDialog.Label.Property=Свойство уровня

LevelPropertyDialog.Label.Attribute=Атрибут

LevelPropertyDialog.Label.Name=Элемент

LevelPropertyDialog.KeyField=&Поле ключа:

LevelPropertyDialog.DataType=Тип &данных:

LevelPropertyDialog.DefaultValue.Edit.Label=&Значение по умолчанию:

LevelPropertyDialog.DefaultValue.Edit.Title=Редактировать

LevelPropertyDialog.DynamicAttributeDialog.Title.Edit=Редактировать атрибут уровня

LevelPropertyDialog.DynamicAttributeDialog.Title.New=Новый атрибут уровня

LevelPropertyDialog.DynamicTable.Button.Add=Добавить&...

LevelPropertyDialog.DynamicTable.Button.Edit=Редакт&ировать...

LevelPropertyDialog.DynamicTable.Button.Remove=&Удалить

LevelPropertyDialog.Label.Expression=Выражение условия

LevelPropertyDialog.Label.LinkTo=&Связать с:

LevelPropertyDialog.MSG.Dynamic.CreateNew=<Создать новый атрибут>

LevelPropertyDialog.MSG.Tooltip=(Отображать все другие значения, не попадающие в эти категории)

LevelPropertyDialog.MSG.DefaultValue=<Значение по умолчанию>

MissLinkDialog.Title=Отсутствует связь между наборами данных

MissLinkDialog.Question=Все группы из других наборов данных должны быть связаны с первичным набором данных. Хотите указать отсутствующие связи для завершения куба?

SetConstraintCommand.setUserProperty=setUserProperty
###########################################################
# Свойства RenameInputDialog
RenameInputDialog.DialogTitle=Переименовать ввод

RenameInputDialog.DialogMessage=Введите новое имя.

RenameInputDialog.Message.BlankName=Имя не может быть пустым.

RenameInputDialog.Message.NumericName=Имя не может быть только числом.

RenameInputDialog.Message.DuplicateName=Имя уже используется.
############################################################
# Свойства ExpressionBuilder
ExpressionProvider.Category.DataSets=Доступные наборы данных

DateGroupDialog.Shell.Title=Уровень группы

DateLevelDialog.Shell.Title=Редактировать уровень даты

DateLevelDialog.Interval.Base=Использовать фиксированное базовое значение для интервала:

DateGroupDialog.Name=&Имя:

DateLevelDialog.Name=&Имя:

DateLevelDialog.Type=&Тип:

DateLevelDialog.Format=&Формат:

DateLevelDialog.KeyField=Поле ключа:

DateLevelDialog.Label.LinkTo=&Связать с:

DateLevelDialog.None=Нет

############################################################
# Свойства действий Cube
NewCubeAction.DataCube=Куб данных

NewCubeAction.trans.cube.new=Создать куб

###########################################################
# Свойства CubePageGenerator
PrimaryDatasetDescriptorProvider.Display.Primary.Dataset.Name=&Первичный набор данных:

CubePageGenerator.List.General=Общие

############################################################
# Свойства FilterListDialog
FilterListDialog.Shell.Title=Фильтр

FilterListDialog.Menu.ModifyProperty=Изменить свойство

FilterListDialog.Button.AddWithDialog=&Добавить...

FilterListDialog.Button.EditWithDialog=&Редактировать...

FilterListDialog.Button.Delete=&Удалить

VirtualField.SharedDimensions=Общие измерения

MeasureDialog.Label.Format=Ф&орматировать как:

MeasureDialog.Button.Format.Edit=&Изменить...

MeasureDialog.Label.Alignment=В&ыравнивание:

LevelPropertyDialog.Label.Format=&Форматировать как:

LevelPropertyDialog.Button.Format.Edit=&Изменить...

LevelStaticAttributeDialog.Error.Message=Элемент не может быть пустым.

LevelStaticAttributeDialog.Label.Expression=В&ыражение условия:

LevelStaticAttributeDialog.Label.Member=&Элемент:

LevelPropertyDialog.Label.Alignment=В&ыравнивание: