dataset.editor.page.query=Запрос

# Конфигурация профиля плагина
#
oda.data.source.id=org.eclipse.birt.report.data.oda.sampledb
#
###############################################################################
# Сообщения NLS
#
plugin.name=Дизайнер примеров БД BIRT
newwizard.name=Источник данных примеров БД BIRT
newwizard.description=Создать профиль подключения для примера базы данных BIRT

wizard.window.title=Новый профиль подключения для примера базы данных

wizard.data.source.page.title=Новый пример источника данных "Classic Models Inc."

profile.propertypage.name=Свойства подключения источника данных примеров БД BIRT
