#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
# Postscript Emitter
PostscriptEmitter.Description=Настройка параметров рендеринга отчета в формате PostScript.

PostscriptEmitter.DisplayName=PostScript (PS)

###########################################################
# Значения отображения опций
OptionDisplayValue.BidiProcessing=Обработка BIDI

OptionDisplayValue.TextWrapping=Перенос текста

OptionDisplayValue.PageOverFlow=Обработка переполнения страницы

OptionDisplayValue.CLIP_CONTENT=Обрезать содержимое

OptionDisplayValue.FIT_TO_PAGE_SIZE=Подогнать под размер страницы

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Вывод на несколько страниц

OptionDisplayValue.ENLARGE_PAGE_SIZE=Увеличить размер страницы

OptionDisplayValue.FontSubstitution=Замена шрифта

OptionDisplayValue.Copies=Количество копий

OptionDisplayValue.Collate=Разобрать по страницам

OptionDisplayValue.Duplex=Двусторонняя печать

OptionDisplayValue.PaperSize=Размер бумаги

OptionDisplayValue.PaperTray=Лоток для бумаги

OptionDisplayValue.ChartDpi=DPI диаграммы

OptionDisplayValue.Resolution=Разрешение

OptionDisplayValue.Scale=Масштаб

OptionDisplayValue.Color=Цвет

OptionDisplayValue.AutoPaperSizeSelection=Автоматический выбор размера бумаги

###########################################################
# Описания опций
OptionDescription.BidiProcessing=Поддерживает двунаправленный текст.

OptionDescription.TextWrapping=Указывает, содержит ли текст переносы строк.

OptionDescription.PageOverFlow=Определяет способ вывода содержимого.

OptionDescription.FontSubstitution=Автоматически выбирает шрифты, если указанный шрифт не может отобразить символ.

OptionDescription.Copies=Количество копий.

OptionDescription.Collate=Разобрать по страницам.

OptionDescription.Duplex=Двусторонняя печать.

OptionDescription.PaperSize=Размер бумаги.

OptionDescription.PaperTray=Лоток для бумаги.

OptionDescription.ChartDpi=DPI для создания диаграмм.

OptionDescription.Resolution=Разрешение.

OptionDescription.Scale=Масштабирование.

OptionDescription.Color=Цвет.

OptionDescription.AutoPaperSizeSelection=Выбирает размер бумаги в зависимости от размера страницы.

OptionDescription.FitToPaper=Подогнать под бумагу.

###########################################################
# Подсказки
Tooltip.ChartDpi=DPI, используемые движком диаграмм для создания диаграмм. Например, 192.