#/*******************************************************************************
# * Copyright (c) 2010 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
# ODP Emitter
ODPEmitter.Description=Настройка параметров рендеринга отчета в формате OpenDocument Presentation.

ODPEmitter.DisplayName=OpenDocument Presentation

###########################################################
# Значения отображения опций
OptionDisplayValue.BidiProcessing=Обработка BIDI

OptionDisplayValue.TextWrapping=Перенос текста

OptionDisplayValue.PageOverFlow=Обработка переполнения страницы

OptionDisplayValue.CLIP_CONTENT=Обрезать содержимое

OptionDisplayValue.FIT_TO_PAGE_SIZE=Подогнать под размер страницы

OptionDisplayValue.OUTPUT_TO_MULTIPLE_PAGES=Вывод на несколько страниц

OptionDisplayValue.ENLARGE_PAGE_SIZE=Увеличить размер страницы

OptionDisplayValue.FontSubstitution=Замена шрифта

OptionDisplayValue.ChartDpi=DPI диаграммы

###########################################################
# Описания опций
OptionDescription.BidiProcessing=Используется обработка BIDI.

OptionDescription.TextWrapping=Текст содержит переносы строк.

OptionDescription.PageOverFlow=Определяет способ вывода содержимого.

OptionDescription.FontSubstitution=Проверка необходимости, поддерживает ли выбранный шрифт данный символ.

OptionDescription.ChartDpi=DPI для создания диаграмм.

###########################################################
# Подсказки
Tooltip.ChartDpi=DPI, используемые движком диаграмм для создания диаграмм. Например, 192.