###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Конфигурация плагина
#
oda.data.source.id=org.eclipse.birt.report.data.oda.jdbc
#
###############################################################################
# Путь к просмотру
###############################################################################
birt-viewer-driver-path=birt/plugins/org.eclipse.birt.report.data.oda.jdbc/drivers

###############################################################################
# Строки NLS
###############################################################################
dataset.editor.page.query=Запрос

datasource.name=Источник данных JDBC

dataset.jdbcselect=SQL SELECT через JDBC

datasource.editor.page.connection=Подключение источника данных

preference.datasetpreview=Набор данных JDBC

preference.bidi.datasource.title =Источник данных JDBC

wizard.data.set.title=Новый набор данных


plugin.name=Плагин BIRT JDBC UI
newwizard.name=Источник данных BIRT JDBC
newwizard.description=Создать профиль подключения источника данных BIRT JDBC

wizard.window.title=Новый профиль источника данных JDBC

wizard.data.source.page.title=Создать новый источник данных

profile.propertypage.name=Источник данных BIRT JDBC