#/*******************************************************************************
# * Copyright (c) 2008 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v2.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-2.0.html
# *
# * Contributors:
# *  Actuate Corporation  - initial API and implementation
# *******************************************************************************/

###########################################################
# Word Emitter
WordEmitter.Description=Настройка параметров рендеринга отчета в формате XML Document 2003.

WordEmitter.DisplayName=Word (DOC)

###########################################################
# Значения отображения опций
OptionDisplayValue.ChartDpi=DPI диаграммы

###########################################################
# Описания опций
OptionDescription.ChartDpi=DPI для создания диаграмм.

###########################################################
# Подсказки
Tooltip.ChartDpi=DPI, используемые движком диаграмм для создания диаграмм. Например, 192.