RadarSeriesImpl.displayName=Ряд данных радара

RadarChart.Txt.DefaultRadarChartTitle=Заголовок радарной диаграммы
RadarChart.Txt.DisplayName=Радар
RadarChart.SubType.Standard=Стандартная радарная диаграмма
RadarChart.SubType.Spider=Сетевая радарная диаграмма
RadarChart.SubType.Bullseye=Точечная радарная диаграмма

RadarChart.Tooltip.InputExpression=Введите выражение, которое будет отображаться как текст легенды для каждого объекта.
RadarChart.Txt.HelpText=Радарные диаграммы отображают текущее значение данных определённой измеряемой величины. Разноцветные секции представляют диапазоны значений измеряемой величины. Стрелки связаны с индикаторами и показывают их значение.
RadarChart.Txt.Description=Стандартные радарные диаграммы содержат круговую сетку, на которую накладываются один или несколько многоугольников рядов или одна или несколько линий рядов.
RadarChart.Txt.SpiderDescription=Сетевые радарные диаграммы содержат многоугольную сетку, на которую накладываются один или несколько многоугольников рядов или одна или несколько линий рядов.
RadarChart.Txt.BullseyeDescription=Точечные радарные диаграммы содержат заполненную круговую сетку, на которую накладываются один или несколько многоугольников рядов или одна или несколько линий рядов.

RadarSeriesAttributeComposite.Lbl.Radius=Ради&ус:
RadarSeriesAttributeComposite.Lbl.StartAngle=&Начальный угол:
RadarSeriesAttributeComposite.Lbl.StopAngle=Конечн&ый угол:
RadarSeriesAttributeSheetImpl.Lbl.Type=Введите следующее:
RadarSeriesAttributeSheetImpl.Lbl.Fill=Заполнение:
RadarSeriesAttributeComposite.Lbl.DialTicks=&Штрихи
RadarSeriesAttributeComposite.Lbl.DialScale=Ш&кала
RadarBaseSeriesComponent.Label.CategoryDefinition=&Определение категории:
RadarSeriesAttributeComposite.Lbl.ShowWeb=Показывать &веб-/радарные надписи

RadarSeriesAttributeComposite.Exception.IllegalArgument=Ряд данных типа {0} является недопустимым аргументом для RadarSeriesAttributeComposite.
RadarSeriesAttributeComposite.Lbl.LinePalette=Использовать &палитру ряда данных как цвет линии
RadarSeriesAttributeComposite.Lbl.FillPoly=Заполнять &полигоны
RadarSeriesAttributeComposite.Lbl.ConnectPoints=Соединять конечные точки наборов данных (полигонально)

RadarSeriesAttributeComposite.Lbl.ShowLinesAsCurves=Показывать &линии как кривые

RadarSeriesMarkerSheet.Label.Markers=&Маркер
RadarSeriesMarkerSheet.GroupLabel.Markers=Маркер

RadarSeriesMarkerSheet.Label.Web=Конфигурация линий диаграммы
RadarSeriesMarkerSheet.Label.Series=Конфигурация линий ряда

Radar.Composite.Label.ScaleCount=Ко&личество шагов шкалы в диаграмме
Radar.Composite.Label.ScaleCountToolTip=Количество шагов шкалы для создания в диаграмме
Radar.Composite.Label.bullsEye=Установить прозрачность цветов точек

Radar.Composite.Label.PlotPercentageToolTip=Процент области построения, необходимый для радара